// Layer 4: dataviews -- the registered recipes the chooser offers and dashboards place
// (catalogue doc §2.4). Seeded from S0 audit A §1 (IDs as the audit's), §3 and §4.
//
// ORDER MATTERS: hosts in column order (Column 1 Candidates, Results, Grade counts,
// Context, Comparisons), then Current's rail, then Trends' rail. matching.ts uses this
// array order as the stable sort key within a tier ("familiar first", then rail order).
//
// Matching model (combinations doc §2): Column 1 and Context views compare against other
// subjects in the school (`subjects`); Column 1 Results views that draw England markers
// compare against `subjects` and `averages`; the geography views compare against
// `averages` only (finding F2: the seeded Column 1 Trends panel carries an override);
// Comparisons compares against a school set (`schools`), focused on a subject or, with no
// subject chip, the school itself.
import type { AudienceTag, CompareKind, Dataview, DataviewId, HostId, MeasureId, Phase, ResultsMeasure } from "./types";

const CP = "src/components/teacher/CandidatesPanels.tsx";
const SP = "src/components/teacher/SubjectPanels.tsx";
const XP = "src/components/teacher/ComparisonsPanels.tsx";
const GP = "src/components/teacher/GradeCountsPanels.tsx";

const PHASES: Phase[] = ["ks4", "ks5"];
const BOTH_DATA = ["academic.candidates", "academic.results"] as Dataview["supports"]["data"];
const RATE_RESULTS: ResultsMeasure[] = ["points", "threshold", "bands"];
// 0.6 snag 3 / 03: the Results pill states a view is offered on (Dataview.resultsMeasures),
// read from the hosts as they are: Column 1 draws SubjectPanels on points / threshold /
// bands and GradeCountsPanels on counts, so its views split by host; Context and
// Comparisons draw every view on all four (falling back to points / the headline on
// counts), so theirs are unset. Data-dependent gaps (Grades needs bands' range control,
// Comparisons' Chart needs 4 years, the donut's R-DONUT-COUNTS-ONLY) stay host rules.
const SUBJECT_PANELS_RESULTS: ResultsMeasure[] = ["points", "threshold", "bands"];
// 0.6 snag 4 / 02: the other axes (Dataview.variants), read from the hosts the same way.
// Context draws every view on each Compare against set (the pre-0.6 page did not vary its
// rail by it), so theirs are unset. Comparisons varies by its comparator kind
// (R-RANKING-SAMPLE, ComparisonsPanels): Number tiles only for a ranking, the maps only for
// a set of schools.

const ENTRIES: MeasureId[] = ["M-KS4-ENTRIES", "M-KS5-ENTRIES"];
const POINTS: MeasureId[] = ["M-KS4-POINTS", "M-KS5-POINTS"];
const THRESHOLD: MeasureId[] = ["M-KS4-THRESHOLD", "M-KS5-THRESHOLD"];
const BANDS: MeasureId[] = ["M-KS4-BANDS", "M-KS5-BANDS"];
const COUNTS: MeasureId[] = ["M-KS4-COUNTS", "M-KS5-COUNTS"];
const HEADLINE: MeasureId[] = ["M-KS4-HEADLINE", "M-KS5-HEADLINE"];
const RESULTS = [...POINTS, ...THRESHOLD, ...BANDS];

const SUBJECT_ACADEMIC: AudienceTag[] = ["subject-level", "academic"];
const SUBJECT_GEOGRAPHY: AudienceTag[] = ["subject-level", "academic", "geography"];
const COMPARISONS: AudienceTag[] = ["subject-level", "whole-school", "academic", "market"];

const SUBJECTS: CompareKind[] = ["subjects"];
const SUBJECTS_AVERAGES: CompareKind[] = ["subjects", "averages"];
const AVERAGES: CompareKind[] = ["averages"];
const SCHOOLS: CompareKind[] = ["schools"];

const LINE_NEEDS_4 = "A line needs 4 real years here; with fewer it shows bars or a change list.";
const GRADES_2YRS = "School grades are published from 2023/24 only (2 years).";

// Host shorthands.
const c1cand = (panel: "current" | "trend", rail: string | null) => ({ id: "teacher.c1.candidates" as const, panel, rail, file: CP });
const c1res = (panel: "current" | "trend", rail: string | null) => ({ id: "teacher.c1.results" as const, panel, rail, file: SP });
const c1cnt = (panel: "current" | "trend", rail: string | null) => ({ id: "teacher.c1.counts" as const, panel, rail, file: GP });
const c2 = (panel: "current" | "trend", rail: string | null) => ({ id: "teacher.c2.context" as const, panel, rail, file: SP });
const c3 = (panel: "current" | "trend", rail: string | null) => ({ id: "teacher.c3.comparisons" as const, panel, rail, file: XP });

const live = { status: "live" as const, verifiedAt: [] as string[] };

export const DATAVIEWS: Dataview[] = [
  // ================================================================ Column 1, Candidates (CandidatesPanels)
  {
    id: "DV-C1-CAND-CUR-TILES",
    label: "Number tiles",
    railIcon: "TilesIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["totals", "rank", "pct_change"],
      dateMode: "single",
      viewType: "numerical",
    },
    params: [],
    titleTemplate: "[subject] Candidates: [year]",
    renderer: "RD-NUMBER-TILES",
    host: c1cand("current", null),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Current panel rework round 1 (Column 1 Current is Number tiles only)",
    rules: ["R-FOCUS-NEVER-FILTERED", "R-KS5-ASAEA-EXCL", "R-QUAL-FAMILY-MATCH", "R-KS4-SUBJECT-DEDUP", "R-RANK-TIES"],
    note: "Railless: Column 1 Candidates' Current has no rail. Tiles: entries, rank in category (only if >1 subject), rank of N subjects at school, change.",
  },
  {
    id: "DV-C1-CAND-TR-INDEXED",
    label: "Indexed",
    railIcon: "IndexedLineIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["index100"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["trendStart", "showFit"],
    titleTemplate: "Entries in [category]",
    titleFallback: "TrendScaleTitle only (indexed): 'Change since [first year]: each line starts at 100 (no change); 110 = 10% more entries, 90 = 10% fewer.'",
    requires: LINE_NEEDS_4,
    renderer: "RD-MULTI-TREND",
    host: c1cand("trend", "Indexed"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Trend redesign (option D2); trends row merge round",
    rules: ["R-TREND-LINE-4YR", "R-INDEX-HEADCOUNTS", "R-PERIOD-TRIM", "R-KS5-ASAEA-EXCL", "R-QUAL-FAMILY-MATCH", "R-KS4-SUBJECT-DEDUP"],
  },
  {
    id: "DV-C1-CAND-TR-ACTUAL",
    label: "Actual",
    railIcon: "TrendLineIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["totals"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["trendStart", "showFit"],
    titleTemplate: "Entries in [category]",
    titleFallback: "TrendScaleTitle only (actual): 'Entries each year, real numbers: one scale for every subject, so small ones sit low.'",
    requires: LINE_NEEDS_4 + " The Actual button is disabled with no line.",
    renderer: "RD-MULTI-TREND",
    host: c1cand("trend", "Actual"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Column 1 qualification match / trend actual numbers round",
    rules: ["R-TREND-LINE-4YR", "R-PERIOD-TRIM", "R-KS5-ASAEA-EXCL", "R-QUAL-FAMILY-MATCH", "R-KS4-SUBJECT-DEDUP"],
  },
  {
    id: "DV-C1-CAND-TR-TABLE",
    label: "Trend table",
    railIcon: "TableIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["totals", "pct_change"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["trendStart"],
    titleTemplate: "Entries in [category], year by year",
    titleFallback: "[subject], year by year",
    renderer: "RD-YEAR-TABLE",
    host: c1cand("trend", "Trend table"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Trend redesign (options E, I); trends row merge round",
    rules: ["R-PERIOD-TRIM", "R-KS5-ASAEA-EXCL", "R-QUAL-FAMILY-MATCH", "R-KS4-SUBJECT-DEDUP"],
  },
  {
    id: "DV-C1-CAND-TR-GEO-CHART",
    label: "Area chart",
    railIcon: "TrendLineIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: AVERAGES,
      numberType: ["index100"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["trendStart"],
    titleTemplate: "[subject] against its LA and England, year by year",
    titleFallback: "Plain heading (not ViewTitle), with TrendScaleTitle indexed under it.",
    requires: "GCSE (9-1) Full Course items only at GCSE (area entries are points-eligible entries); LA and England lines (region in the table).",
    renderer: "RD-GEOGRAPHY-VIEW",
    host: c1cand("trend", "Area chart"),
    audience: SUBJECT_GEOGRAPHY,
    ...live,
    origin: "Candidates live review Part 5; trends row merge round",
    rules: ["R-GEO-APPLIES", "R-GEO-POINTS-ELIGIBLE", "R-MIN-SCHOOLS", "R-KS5-ENGLAND-EXACT", "R-INDEX-HEADCOUNTS"],
    note: "Placement mismatch F2: Column 1 declares subjects-in-school only; the seeded Column 1 Trends panel carries an override (LA, region, England).",
  },
  {
    id: "DV-C1-CAND-TR-GEO-TABLE",
    label: "Change table",
    railIcon: "TableIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: AVERAGES,
      numberType: ["totals", "pct_change"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["changeStart"],
    titleTemplate: "[subject]: change against its LA, region and England",
    requires: "GCSE (9-1) Full Course items only at GCSE (area entries are points-eligible entries).",
    renderer: "RD-GEOGRAPHY-VIEW",
    host: c1cand("trend", "Change table"),
    audience: SUBJECT_GEOGRAPHY,
    ...live,
    origin: "Candidates live review Part 5; trends row merge round",
    rules: ["R-GEO-APPLIES", "R-GEO-POINTS-ELIGIBLE", "R-MIN-SCHOOLS", "R-KS5-ENGLAND-EXACT"],
    note: "Placement mismatch F2 (as Area chart).",
  },
  {
    id: "DV-C1-CAND-TR-CHANGELIST",
    label: "Ranked change",
    railIcon: "HorizontalBarsIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["pct_change"],
      dateMode: "trend",
      viewType: "ranking",
    },
    params: ["changeStart"],
    titleTemplate: "Entries in [category]: % change since [year], ranked",
    titleFallback: "Entries: % change since [year]",
    renderer: "RD-CHANGE-LIST",
    host: c1cand("trend", null),
    audience: SUBJECT_ACADEMIC,
    status: "draft",
    verifiedAt: [],
    origin: "Trend & % change redesign",
    rules: ["R-KS5-ASAEA-EXCL", "R-QUAL-FAMILY-MATCH"],
    note: "Dead branch (audit A §0.5): Column 1's % change half is always the geography view, so CandidatesPanels.tsx:404-417 is unreachable.",
  },
  {
    id: "DV-C1-CAND-TR-CHANGETABLE",
    label: "Change table (category)",
    railIcon: "TableIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["totals", "pct_change"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["changeStart"],
    titleTemplate: "Entries in [category]: [year] against the latest year, with the change",
    titleFallback: "Entries by year, since [year]",
    renderer: "RD-YEAR-TABLE",
    host: c1cand("trend", null),
    audience: SUBJECT_ACADEMIC,
    status: "draft",
    verifiedAt: [],
    origin: "Trend & % change redesign",
    rules: ["R-KS5-ASAEA-EXCL", "R-QUAL-FAMILY-MATCH"],
    note: "Dead branch (audit A §0.5): CandidatesPanels.tsx:393-403 is unreachable.",
  },

  // ================================================================ Column 1, Results on points / threshold / bands (SubjectPanels)
  {
    id: "DV-C1-RES-CUR-TILES",
    label: "Number tiles",
    railIcon: "TilesIcon",
    resultsMeasures: SUBJECT_PANELS_RESULTS,
    measures: RESULTS,
    supports: {
      data: ["academic.results"],
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS_AVERAGES,
      numberType: ["points", "rate", "rank", "change_points", "change_pp", "totals"],
      dateMode: "single",
      viewType: "numerical",
    },
    params: ["band:range"],
    titleTemplate: "",
    titleFallback: "None: the wrapper title is suppressed for tiles (SubjectPanels.tsx:1042).",
    requires: "England average and gap tiles only with a same-year England figure: points (and bands, from grade geography); threshold shows the rank tile only.",
    renderer: "RD-NUMBER-TILES",
    host: c1res("current", "Number tiles"),
    audience: SUBJECT_GEOGRAPHY,
    ...live,
    origin: "Teacher view round 6; grade bands frontend round (bands variant)",
    rules: ["R-SAME-YEAR-BENCH", "R-NO-GRADE-RATE-GEO", "R-BANDS-ENGLAND-BENCH", "R-NON-GRADES-EXCL", "R-RANK-TIES", "R-KS5-ENGLAND-EXACT"],
    note: "One dataview for the audit's two rows (plain and bands variant): on bands the tiles are met count 'of {n} graded entries at {range}', rate and England gap (placement mismatch M3/M5).",
  },
  {
    id: "DV-C1-RES-CUR-GRADES",
    label: "Grades (pick a range)",
    railIcon: "GradesIcon",
    resultsMeasures: ["bands"],
    measures: BANDS,
    supports: {
      data: ["academic.results"],
      results: ["bands"],
      phases: PHASES,
      focus: ["subject"],
      compare: AVERAGES,
      numberType: ["rate"],
      dateMode: "single",
      viewType: "graph",
    },
    params: ["band:range", "bandPending"],
    titleTemplate: "",
    titleFallback: "None (wrapper suppressed). No range: 'Pick a range to see a rate: open Grades and click one grade, then another.'",
    requires: GRADES_2YRS,
    renderer: "RD-GRADE-DISTRIBUTION",
    host: c1res("current", "Grades (pick a range)"),
    audience: SUBJECT_GEOGRAPHY,
    ...live,
    origin: "Grade bands frontend round",
    rules: ["R-NON-GRADES-EXCL", "R-GRADE-SCALE-MATCH", "R-BANDS-ENGLAND-BENCH", "R-MIN-SCHOOLS"],
    note: "England share ticks per grade (placement mismatch M5).",
  },
  {
    id: "DV-C1-RES-CUR-BAR",
    label: "Bar chart",
    railIcon: "HorizontalBarsIcon",
    resultsMeasures: SUBJECT_PANELS_RESULTS,
    measures: RESULTS,
    supports: {
      data: ["academic.results"],
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS_AVERAGES,
      numberType: ["points", "rate"],
      dateMode: "single",
      viewType: "ranking",
    },
    params: ["band:range"],
    titleTemplate: "Results in [category]",
    titleFallback: "None when the category has one subject (plain p, not ViewTitle).",
    requires: "National average marker only where a same-year England figure exists (not on Grade 4+ / A*-E).",
    renderer: "RD-VIEW-CHART",
    host: c1res("current", "Bar chart"),
    audience: SUBJECT_GEOGRAPHY,
    ...live,
    origin: "Teacher view round 6",
    rules: ["R-SAME-YEAR-BENCH", "R-NO-GRADE-RATE-GEO", "R-KS5-ENGLAND-EXACT", "R-QUAL-FAMILY-MATCH", "R-KS5-ASAEA-EXCL", "R-KS4-SUBJECT-DEDUP"],
  },
  {
    id: "DV-C1-RES-CUR-TABLE",
    label: "Sortable table",
    railIcon: "RankListIcon",
    resultsMeasures: SUBJECT_PANELS_RESULTS,
    measures: RESULTS,
    supports: {
      data: ["academic.results"],
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS_AVERAGES,
      numberType: ["points", "rate", "change_points", "change_pp"],
      dateMode: "single",
      viewType: "table",
    },
    params: ["sort", "band:range"],
    titleTemplate: "Results in [category]",
    titleFallback: "None when the category has one subject.",
    requires: "Delta column is 'vs National' with an England figure, else 'vs last year'.",
    renderer: "RD-SORT-TABLE",
    host: c1res("current", "Sortable table"),
    audience: SUBJECT_GEOGRAPHY,
    ...live,
    origin: "Teacher view round 6",
    rules: ["R-PREV-YEAR-FALLBACK", "R-SAME-YEAR-BENCH", "R-NO-GRADE-RATE-GEO", "R-KS5-ENGLAND-EXACT", "R-QUAL-FAMILY-MATCH"],
  },
  {
    id: "DV-C1-RES-TR-CHART",
    label: "Chart",
    railIcon: "TrendLineIcon",
    resultsMeasures: SUBJECT_PANELS_RESULTS,
    measures: RESULTS,
    supports: {
      data: ["academic.results"],
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["points", "rate", "change_points", "change_pp"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["trendStart", "showFit", "legendHidden", "band:range"],
    titleTemplate: "Results in [category]: each subject's line",
    titleFallback: "[subject], each year",
    requires: LINE_NEEDS_4 + " Grade 4+ / A*-E and bands have 2 school years, so they show the pp change list.",
    renderer: "RD-MULTI-TREND",
    host: c1res("trend", "Chart"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Trend redesign; trends row merge round",
    rules: ["R-TREND-LINE-4YR", "R-PERIOD-TRIM", "R-THRESHOLD-PERIODS", "R-INDEX-HEADCOUNTS", "R-QUAL-FAMILY-MATCH", "R-KS5-ASAEA-EXCL"],
    note: "Never indexed (a mean measure). Below 4 years the change list is in the measure's own units (pp / points).",
  },
  {
    id: "DV-C1-RES-TR-TABLE",
    label: "Trend table",
    railIcon: "TableIcon",
    resultsMeasures: SUBJECT_PANELS_RESULTS,
    measures: RESULTS,
    supports: {
      data: ["academic.results"],
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["points", "rate", "change_points", "change_pp"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["trendStart", "band:range"],
    titleTemplate: "Results in [category], year by year",
    titleFallback: "[subject], year by year",
    renderer: "RD-YEAR-TABLE",
    host: c1res("trend", "Trend table"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Trend redesign; trends row merge round",
    rules: ["R-PERIOD-TRIM", "R-THRESHOLD-PERIODS", "R-QUAL-FAMILY-MATCH"],
  },
  {
    id: "DV-C1-RES-TR-MAP",
    label: "Map",
    railIcon: "MapPinIcon",
    resultsMeasures: SUBJECT_PANELS_RESULTS,
    measures: [...POINTS, ...BANDS],
    supports: {
      data: ["academic.results"],
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SCHOOLS,
      numberType: ["points"],
      dateMode: "single",
      viewType: "map",
    },
    params: ["mapRank"],
    titleTemplate: "[subject] at each comparator school, on the map",
    requires: "Needs a focus subject with a map chip and the school's location; falls back to Chart when the focus loses its chip.",
    renderer: "RD-RANKINGS-MAP",
    host: c1res("trend", "Map"),
    audience: ["subject-level", "academic", "market"],
    ...live,
    origin: "Teacher view round 7 (map in Trends)",
    rules: ["R-IGCSE-EXCL", "R-POINTS-SAME-QUAL"],
    note: "Placement mismatch M4: sits in Column 1 Trends but compares a school set and shows one year (the map's own toggle). Declared honestly as schools / single, so the seeded Column 1 Trends panel does not match it.",
  },
  {
    id: "DV-C1-RES-TR-GEO-CHART",
    label: "Area chart",
    railIcon: "TrendLineIcon",
    resultsMeasures: SUBJECT_PANELS_RESULTS,
    measures: POINTS,
    supports: {
      data: ["academic.results"],
      results: ["points"],
      phases: PHASES,
      focus: ["subject"],
      compare: AVERAGES,
      numberType: ["points"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["trendStart"],
    titleTemplate: "[subject] against its LA and England, year by year",
    titleFallback: "Plain heading; no TrendScaleTitle (not indexed).",
    requires: "Average points only; at GCSE, GCSE (9-1) Full Course items only.",
    renderer: "RD-GEOGRAPHY-VIEW",
    host: c1res("trend", "Area chart"),
    audience: SUBJECT_GEOGRAPHY,
    ...live,
    origin: "Candidates live review Part 5; Post-16 Part C",
    rules: ["R-NO-GRADE-RATE-GEO", "R-KS4-POINTS-GCSE-FULL", "R-KS5-ENGLAND-EXACT", "R-MIN-SCHOOLS", "R-GEO-APPLIES"],
    note: "Placement mismatch F2. On threshold or bands the host shows the not-applicable note, so the view supports points only.",
  },
  {
    id: "DV-C1-RES-TR-GEO-TABLE",
    label: "Change table",
    railIcon: "TableIcon",
    resultsMeasures: SUBJECT_PANELS_RESULTS,
    measures: POINTS,
    supports: {
      data: ["academic.results"],
      results: ["points"],
      phases: PHASES,
      focus: ["subject"],
      compare: AVERAGES,
      numberType: ["points", "change_points"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["changeStart"],
    titleTemplate: "[subject]: change against its LA, region and England",
    requires: "Average points only; at GCSE, GCSE (9-1) Full Course items only.",
    renderer: "RD-GEOGRAPHY-VIEW",
    host: c1res("trend", "Change table"),
    audience: SUBJECT_GEOGRAPHY,
    ...live,
    origin: "Candidates live review Part 5; Post-16 Part C",
    rules: ["R-NO-GRADE-RATE-GEO", "R-KS4-POINTS-GCSE-FULL", "R-KS5-ENGLAND-EXACT", "R-MIN-SCHOOLS", "R-GEO-APPLIES"],
    note: "Placement mismatch F2 (as Area chart). S3b: the Change column shows the change in points alone, not a % (R-NUMBER-TYPE-HONESTY)."
  },

  // ================================================================ Column 1, Results on Grade counts (GradeCountsPanels)
  {
    id: "DV-C1-CNT-CUR-DIST",
    label: "Grade distribution",
    railIcon: "GradesIcon",
    resultsMeasures: ["counts"],
    measures: COUNTS,
    supports: {
      data: ["academic.results"],
      results: ["counts"],
      phases: PHASES,
      focus: ["subject"],
      compare: AVERAGES,
      numberType: ["totals", "rate"],
      dateMode: "single",
      viewType: "graph",
    },
    params: ["bandPending", "span"],
    titleTemplate: "",
    titleFallback: "None; the tag reads 'Grade counts [year]' (not 'Current', no 'Data [year]').",
    requires: GRADES_2YRS,
    renderer: "RD-GRADE-DISTRIBUTION",
    host: c1cnt("current", null),
    audience: SUBJECT_GEOGRAPHY,
    ...live,
    origin: "Grade bands frontend round (Grade counts)",
    rules: ["R-NON-GRADES-EXCL", "R-MIN-SCHOOLS", "R-THRESHOLD-PERIODS"],
    note: "Railless. England share ticks (placement mismatch M5). The tag is inconsistent with every other Current tag (audit §4).",
  },
  {
    id: "DV-C1-CNT-TR-SPREAD",
    label: "Spread by year",
    railIcon: "GradesIcon",
    resultsMeasures: ["counts"],
    measures: COUNTS,
    supports: {
      data: ["academic.results"],
      results: ["counts"],
      phases: PHASES,
      focus: ["subject"],
      compare: [],
      numberType: ["totals", "rate"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["compareFrom"],
    titleTemplate: "[subject]'s spread of grades: [year] against [compare year], grade by grade",
    requires: GRADES_2YRS + " A second year is needed to compare.",
    renderer: "RD-GRADE-DISTRIBUTION",
    host: c1cnt("trend", "Spread by year"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Grade bands frontend round (Grade counts)",
    rules: ["R-NON-GRADES-EXCL", "R-THRESHOLD-PERIODS"],
  },
  {
    id: "DV-C1-CNT-TR-CHANGETABLE",
    label: "Change table",
    railIcon: "TableIcon",
    resultsMeasures: ["counts"],
    measures: COUNTS,
    supports: {
      data: ["academic.results"],
      results: ["counts"],
      phases: PHASES,
      focus: ["subject"],
      compare: [],
      numberType: ["totals"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["changeFrom"],
    titleTemplate: "[subject]'s entries at each grade: [change year] against [year], with the change",
    requires: GRADES_2YRS + " A second year is needed to measure a change.",
    renderer: "RD-YEAR-TABLE",
    host: c1cnt("trend", "Change table"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Grade bands frontend round (Grade counts)",
    rules: ["R-NON-GRADES-EXCL", "R-THRESHOLD-PERIODS"],
  },

  // ================================================================ Column 2, Context (SubjectPanels)
  {
    id: "DV-C2-CUR-DONUT",
    label: "Share (donut)",
    railIcon: "DonutIcon",
    measures: [...ENTRIES, ...BANDS],
    supports: {
      data: BOTH_DATA,
      results: ["bands"],
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["market_share"],
      dateMode: "single",
      viewType: "donut",
    },
    params: ["yearIdx", "against:context", "chosen:context"],
    titleTemplate: "Entries in [subject] as a proportion of [comparison-group]",
    titleFallback: "Bands: 'Entries at [range] as a proportion of graded entries in [comparison-group]'. [comparison-group] = category label | 'your selected subjects' | 'all subjects' (fallback 'its subject category').",
    requires: "Results: Grade bands with a range picked (R-DONUT-COUNTS-ONLY).",
    renderer: "RD-SHARE-DONUT",
    host: c2("current", "Share (donut)"),
    audience: ["subject-level", "academic", "market"],
    ...live,
    origin: "Teacher view round 6 §4.2; Post-16 Part D (group totals)",
    rules: ["R-DONUT-COUNTS-ONLY", "R-SELF-INCLUSIVE-GROUP", "R-KS5-ASAEA-EXCL", "R-QUAL-FAMILY-MATCH", "R-FOCUS-NEVER-FILTERED"],
    note: "On points and rates the host keeps the button disabled ('Share is only meaningful for candidate numbers'), so the view supports results: bands only.",
  },
  {
    id: "DV-C2-CUR-BARS",
    label: "Bar chart",
    railIcon: "VerticalBarsIcon",
    measures: [...ENTRIES, ...RESULTS],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["totals", "points", "rate"],
      dateMode: "single",
      viewType: "ranking",
    },
    params: ["yearIdx", "against:context", "chosen:context"],
    titleTemplate: "[Entries|Results] by subject in [comparison-group]",
    titleFallback: "None on Results without a compare-against label. Provisional wording (SubjectPanels.tsx:489-491).",
    renderer: "RD-VERTICAL-BARS",
    host: c2("current", "Bar chart"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Current panel rework round 1 (Column 1's VerticalBars moved to Context)",
    rules: ["R-QUAL-FAMILY-MATCH", "R-KS5-ASAEA-EXCL", "R-POINTS-SAME-QUAL", "R-POINTS-WEIGHTED", "R-MEASURE-FALLBACK"],
    note: "Default Context Current view. On Grade counts / bands without a range the host shows points (R-MEASURE-FALLBACK, mismatch M6).",
  },
  {
    id: "DV-C2-CUR-LIST",
    label: "Ranked list",
    railIcon: "RankListIcon",
    measures: [...ENTRIES, ...RESULTS],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["totals", "points", "rate", "rank"],
      dateMode: "single",
      viewType: "ranking",
    },
    params: ["yearIdx", "against:context", "chosen:context"],
    titleTemplate: "[Entries|Results] by subject in [comparison-group]",
    titleFallback: "Provisional wording (SubjectPanels.tsx:489-491).",
    renderer: "RD-RANKED-LIST",
    host: c2("current", "Ranked list"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Current panel rework round 1 (moved from Column 1)",
    rules: ["R-QUAL-FAMILY-MATCH", "R-KS5-ASAEA-EXCL", "R-POINTS-SAME-QUAL", "R-MEASURE-FALLBACK"],
  },
  {
    id: "DV-C2-CUR-TABLE",
    label: "Sortable table",
    railIcon: "TableIcon",
    measures: [...ENTRIES, ...RESULTS],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["rank", "totals", "change_points", "change_pp"],
      dateMode: "single",
      viewType: "table",
    },
    params: ["yearIdx", "sort", "against:context", "chosen:context"],
    titleTemplate: "[Entries|Results] by subject in [comparison-group]",
    titleFallback: "Provisional wording (SubjectPanels.tsx:489-491).",
    renderer: "RD-SORT-TABLE",
    host: c2("current", "Sortable table"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Teacher view round 6",
    rules: ["R-SELF-INCLUSIVE-GROUP", "R-QUAL-FAMILY-MATCH", "R-KS5-ASAEA-EXCL", "R-MEASURE-FALLBACK", "R-RANK-TIES"],
    note: "Delta 'vs average' (the group average); leading rank, no value column.",
  },
  {
    id: "DV-C2-TR-INDEXED",
    label: "Indexed",
    railIcon: "IndexedLineIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["index100"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["trendStart", "showFit", "legendHidden", "against:context"],
    titleTemplate: "Entries in [comparison-group]",
    titleFallback: "TrendScaleTitle (indexed) under the scope; none without a group.",
    requires: LINE_NEEDS_4,
    renderer: "RD-MULTI-TREND",
    host: c2("trend", "Indexed"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Trend redesign; trends row merge round",
    rules: ["R-TREND-LINE-4YR", "R-INDEX-HEADCOUNTS", "R-PERIOD-TRIM", "R-KS5-ASAEA-EXCL"],
    note: "On 'All subjects' the card is focus vs group average (page.tsx:1922, SubjectPanels.tsx:726-738).",
  },
  {
    id: "DV-C2-TR-CHART",
    label: "Chart",
    railIcon: "TrendLineIcon",
    measures: RESULTS,
    supports: {
      data: ["academic.results"],
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["points", "rate", "change_points", "change_pp"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["trendStart", "showFit", "legendHidden", "against:context"],
    titleTemplate: "Results in [comparison-group]: each subject's line",
    titleFallback: "[subject], each year",
    requires: LINE_NEEDS_4,
    renderer: "RD-MULTI-TREND",
    host: c2("trend", "Chart"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Trend redesign; trends row merge round",
    rules: ["R-TREND-LINE-4YR", "R-PERIOD-TRIM", "R-THRESHOLD-PERIODS", "R-POINTS-SAME-QUAL", "R-MEASURE-FALLBACK"],
  },
  {
    id: "DV-C2-TR-ACTUAL",
    label: "Actual",
    railIcon: "TrendLineIcon",
    measures: ENTRIES,
    supports: {
      data: ["academic.candidates"],
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["totals"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["trendStart", "showFit", "legendHidden", "against:context"],
    titleTemplate: "Entries in [comparison-group]",
    titleFallback: "TrendScaleTitle (actual) under the scope.",
    requires: LINE_NEEDS_4 + " Disabled with no line.",
    renderer: "RD-MULTI-TREND",
    host: c2("trend", "Actual"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Column 1 qualification match / trend actual numbers round",
    rules: ["R-TREND-LINE-4YR", "R-PERIOD-TRIM", "R-KS5-ASAEA-EXCL"],
  },
  {
    id: "DV-C2-TR-TABLE",
    label: "Trend table",
    railIcon: "TableIcon",
    measures: [...ENTRIES, ...RESULTS],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["totals", "points", "rate"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["trendStart", "legendHidden", "against:context"],
    titleTemplate: "[Entries|Results] in [comparison-group], year by year",
    titleFallback: "[subject], year by year",
    renderer: "RD-YEAR-TABLE",
    host: c2("trend", "Trend table"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Trend redesign; trends row merge round",
    rules: ["R-PERIOD-TRIM", "R-KS5-ASAEA-EXCL", "R-MEASURE-FALLBACK"],
  },
  {
    id: "DV-C2-TR-CHANGELIST",
    label: "Ranked change",
    railIcon: "HorizontalBarsIcon",
    measures: [...ENTRIES, ...RESULTS],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["pct_change", "change_points", "change_pp"],
      dateMode: "trend",
      viewType: "ranking",
    },
    params: ["changeStart", "against:context"],
    titleTemplate: "[Entries|Results] in [comparison-group]: [change-word] since [year], ranked",
    titleFallback: "[Entries|Results]: [% change|change in points|change in percentage points] since [year]",
    renderer: "RD-CHANGE-LIST",
    host: c2("trend", "Ranked change"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Trend & % change redesign (option H)",
    rules: ["R-NUMBER-TYPE-HONESTY", "R-KS5-ASAEA-EXCL", "R-MEASURE-FALLBACK"],
    note: "S3b: % change on entries; change in points on average point score; change in percentage points on rates (R-NUMBER-TYPE-HONESTY).",
  },
  {
    id: "DV-C2-TR-CHANGETABLE",
    label: "Change table",
    railIcon: "TableIcon",
    measures: [...ENTRIES, ...RESULTS],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject"],
      compare: SUBJECTS,
      numberType: ["totals", "points", "rate", "pct_change", "change_points", "change_pp"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["changeStart", "against:context"],
    titleTemplate: "[Entries|Results] in [comparison-group]: [year] against the latest year, ranked by change",
    titleFallback: "[Entries|Results] by year, since [year]",
    renderer: "RD-YEAR-TABLE",
    host: c2("trend", "Change table"),
    audience: SUBJECT_ACADEMIC,
    ...live,
    origin: "Trend & % change redesign",
    rules: ["R-NUMBER-TYPE-HONESTY", "R-KS5-ASAEA-EXCL", "R-MEASURE-FALLBACK"],
  },

  // ================================================================ Column 3, Comparisons (ComparisonsPanels)
  {
    id: "DV-C3-CUR-TILES",
    variants: { comparator: ["ranking"] },
    label: "Number tiles",
    railIcon: "TilesIcon",
    measures: HEADLINE,
    supports: {
      data: BOTH_DATA,
      results: ["points", "threshold", "bands", "counts"],
      phases: PHASES,
      focus: ["school"],
      compare: SCHOOLS,
      numberType: ["points", "rank"],
      dateMode: "single",
      viewType: "numerical",
    },
    params: ["set:rankings", "chooser:rankings"],
    titleTemplate: "[school]'s rank in the [set]: [measure]",
    titleFallback: "Provisional wording (ComparisonsPanels.tsx:312).",
    requires: "Ranking sets only (the default there); always the whole-school headline.",
    renderer: "RD-NUMBER-TILES",
    host: c3("current", "Number tiles"),
    audience: ["whole-school", "academic", "market"],
    ...live,
    origin: "Snagging round 1 Part 4 (ranking sets)",
    rules: ["R-RANKING-SAMPLE", "R-RANK-TIES", "R-IGCSE-EXCL"],
    note: "Offered on Candidates and Results columns alike because it shows the whole-school headline (Attainment 8 / A-level points per entry) in both modes; the ranking's own measure, never the column's.",
  },
  {
    id: "DV-C3-CUR-MAP",
    variants: { comparator: ["schools"] },
    label: "Map",
    railIcon: "MapPinIcon",
    measures: [...ENTRIES, ...POINTS, ...HEADLINE],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject", "school"],
      compare: SCHOOLS,
      numberType: ["points", "totals"],
      dateMode: "single",
      viewType: "map",
    },
    params: ["set:rankings", "chooser:rankings", "mapCaption", "mapRank"],
    titleTemplate: "[subject] [measure] by school, on the map",
    titleFallback: "[headline] by school, on the map (no subject chip). Provisional wording.",
    requires: "Not for ranking sets; needs the school's location.",
    renderer: "RD-RANKINGS-MAP",
    host: c3("current", "Map"),
    audience: COMPARISONS,
    ...live,
    origin: "Teacher view round 7 (Comparisons map)",
    rules: ["R-IGCSE-EXCL", "R-RANKING-SAMPLE", "R-POINTS-SAME-QUAL", "R-MEASURE-FALLBACK"],
    note: "Default Comparisons Current view. With no subject chip on Results the focus switches to the school's headline (mismatch M7).",
  },
  {
    id: "DV-C3-CUR-BAR",
    label: "Bar chart",
    railIcon: "HorizontalBarsIcon",
    measures: [...ENTRIES, ...RESULTS, ...HEADLINE],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject", "school"],
      compare: SCHOOLS,
      numberType: ["points", "rate", "totals"],
      dateMode: "single",
      viewType: "ranking",
    },
    params: ["set:rankings", "chooser:rankings"],
    titleTemplate: "[Entries|Results] by school in the [set]",
    titleFallback: "Ranking measure: '[measure]: [school] against the [set]'s average'. Provisional wording.",
    renderer: "RD-VIEW-CHART",
    host: c3("current", "Bar chart"),
    audience: COMPARISONS,
    ...live,
    origin: "Teacher view round 7",
    rules: ["R-COMPARATOR-NO-FIGURE", "R-COMPARATOR-RATE-PER-QUAL", "R-IGCSE-EXCL", "R-RANKING-SAMPLE", "R-FOCUS-NEVER-FILTERED", "R-MEASURE-FALLBACK"],
  },
  {
    id: "DV-C3-CUR-RANKING",
    label: "Ranking",
    railIcon: "RankListIcon",
    measures: [...ENTRIES, ...RESULTS, ...HEADLINE],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject", "school"],
      compare: SCHOOLS,
      numberType: ["points", "rate", "totals", "rank"],
      dateMode: "single",
      viewType: "table",
    },
    params: ["set:rankings", "chooser:rankings"],
    titleTemplate: "Schools ranked by [subject] [measure] in the [set]",
    titleFallback: "Schools ranked by [headline] in the [set]. Provisional wording.",
    renderer: "RD-SCHOOL-RANKING-TABLE",
    host: c3("current", "Ranking"),
    audience: COMPARISONS,
    ...live,
    origin: "Teacher view round 7 §9",
    rules: ["R-COMPARATOR-NO-FIGURE", "R-RANK-TIES", "R-IGCSE-EXCL", "R-COMPARATOR-RATE-PER-QUAL", "R-FOCUS-NEVER-FILTERED", "R-MEASURE-FALLBACK"],
  },
  {
    id: "DV-C3-TR-CHART",
    label: "Chart",
    railIcon: "TrendLineIcon",
    measures: [...ENTRIES, ...RESULTS, ...HEADLINE],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject", "school"],
      compare: SCHOOLS,
      numberType: ["points", "rate", "totals"],
      dateMode: "trend",
      viewType: "graph",
    },
    params: ["versusChoice", "trendStart", "showFit", "set:rankings"],
    titleTemplate: "This school's [measure] against [versus], year by year",
    titleFallback: "[versus] = a school's name | 'average across this set ([n] schools)' | 'average of the schools shown' | 'average across [set]'.",
    requires: "Below 4 real years the Chart button is hidden and the panel shows the table only.",
    renderer: "RD-TREND-CHART",
    host: c3("trend", "Chart"),
    audience: COMPARISONS,
    ...live,
    origin: "Teacher view round 7; trends row merge round",
    rules: ["R-TREND-LINE-4YR", "R-RANKING-SAMPLE", "R-PERIOD-TRIM", "R-IGCSE-EXCL", "R-MEASURE-FALLBACK"],
    note: "Compares with the set's average or one named school (vs: pill); mismatch M8 (set implies its own average).",
  },
  {
    id: "DV-C3-TR-TABLE",
    label: "Trend table",
    railIcon: "TableIcon",
    measures: [...ENTRIES, ...RESULTS, ...HEADLINE],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject", "school"],
      compare: SCHOOLS,
      numberType: ["totals", "points", "rate"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["trendStart", "set:rankings"],
    titleTemplate: "Every school in the [set]: [measure], year by year",
    renderer: "RD-YEAR-TABLE",
    host: c3("trend", "Trend table"),
    audience: COMPARISONS,
    ...live,
    origin: "Trend redesign; trends row merge round",
    rules: ["R-PERIOD-TRIM", "R-COMPARATOR-NO-FIGURE", "R-IGCSE-EXCL", "R-MEASURE-FALLBACK"],
  },
  {
    id: "DV-C3-TR-MAP",
    variants: { comparator: ["schools"] },
    label: "Trend map",
    railIcon: "MapPinIcon",
    measures: [...ENTRIES, ...RESULTS, ...HEADLINE],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject", "school"],
      compare: SCHOOLS,
      numberType: ["change_points", "change_pp", "totals"],
      dateMode: "trend",
      viewType: "map",
    },
    params: ["trendStart", "set:rankings"],
    titleTemplate: "Change in [measure] since [year], coloured by school",
    titleFallback: "[year] falls back to 'the first year'.",
    requires: "Not for ranking sets; needs the school's location and 2 or more years.",
    renderer: "RD-RANKINGS-MAP",
    host: c3("trend", "Trend map"),
    audience: COMPARISONS,
    ...live,
    origin: "Trends row merge round (Trend map / Change map labels)",
    rules: ["R-RANKING-SAMPLE", "R-IGCSE-EXCL", "R-MEASURE-FALLBACK"],
  },
  {
    id: "DV-C3-TR-CHANGELIST",
    label: "Ranked bars",
    railIcon: "HorizontalBarsIcon",
    measures: [...ENTRIES, ...RESULTS, ...HEADLINE],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject", "school"],
      compare: SCHOOLS,
      numberType: ["pct_change", "change_points", "change_pp"],
      dateMode: "trend",
      viewType: "ranking",
    },
    params: ["changeStart", "set:rankings"],
    titleTemplate: "[change-of-measure] since [year], ranked against the [set]",
    renderer: "RD-CHANGE-LIST",
    host: c3("trend", "Ranked bars"),
    audience: COMPARISONS,
    ...live,
    origin: "Trend & % change redesign (option H)",
    rules: ["R-NUMBER-TYPE-HONESTY", "R-COMPARATOR-NO-FIGURE", "R-IGCSE-EXCL", "R-MEASURE-FALLBACK"],
    note: "S3b: % change on entries; change in points on average point score; change in percentage points on rates (R-NUMBER-TYPE-HONESTY).",
  },
  {
    id: "DV-C3-TR-CHANGETABLE",
    label: "Change table",
    railIcon: "TableIcon",
    measures: [...ENTRIES, ...RESULTS, ...HEADLINE],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject", "school"],
      compare: SCHOOLS,
      numberType: ["totals", "points", "rate", "pct_change", "change_points", "change_pp"],
      dateMode: "trend",
      viewType: "table",
    },
    params: ["changeStart", "set:rankings"],
    titleTemplate: "Every school in the [set]: [year] against the latest year, ranked by change",
    renderer: "RD-YEAR-TABLE",
    host: c3("trend", "Change table"),
    audience: COMPARISONS,
    ...live,
    origin: "Trend & % change redesign",
    rules: ["R-NUMBER-TYPE-HONESTY", "R-COMPARATOR-NO-FIGURE", "R-IGCSE-EXCL", "R-MEASURE-FALLBACK"],
  },
  {
    id: "DV-C3-TR-CHANGEMAP",
    variants: { comparator: ["schools"] },
    label: "Change map",
    railIcon: "MapPinIcon",
    measures: [...ENTRIES, ...RESULTS, ...HEADLINE],
    supports: {
      data: BOTH_DATA,
      results: RATE_RESULTS,
      phases: PHASES,
      focus: ["subject", "school"],
      compare: SCHOOLS,
      numberType: ["pct_change", "change_points", "change_pp"],
      dateMode: "trend",
      viewType: "map",
    },
    params: ["changeStart", "set:rankings"],
    titleTemplate: "[change-of-measure] since [year], coloured by school",
    requires: "Not for ranking sets; needs the school's location and 2 or more years.",
    renderer: "RD-RANKINGS-MAP",
    host: c3("trend", "Change map"),
    audience: COMPARISONS,
    ...live,
    origin: "Comparisons change map colour scale round",
    note: "S3b: a count keeps the fixed ±% scale (forcedColourMode trend); points and rates colour by the absolute change on the set's own range (trend_absolute), keyed 'Change' (R-NUMBER-TYPE-HONESTY).",
    rules: ["R-NUMBER-TYPE-HONESTY", "R-RANKING-SAMPLE", "R-IGCSE-EXCL", "R-MEASURE-FALLBACK"],
  },
];

export const DATAVIEW_IDS: DataviewId[] = DATAVIEWS.map((d) => d.id);

// The registered dataview a host's rail entry selects: the host, its panel and the label
// on the host's own rail button (host.rail). The one mapping between a rail button and a
// dataview id -- the config renderer reads it from here rather than keeping a second list
// (0.6 E). Railless views (rail null) have no button to map.
export function dataviewForRail(host: HostId, panel: "current" | "trend", label: string): Dataview | undefined {
  return DATAVIEWS.find((d) => d.host.id === host && d.host.panel === panel && d.host.rail === label);
}
