// Layer 1: rules -- what a number is allowed to be (catalogue doc §2.1).
//
// Seeded from the S0 audit (A §2, B §1): the twelve rules the catalogue doc named,
// confirmed or corrected, plus every rule the audit found in code. `enforcedIn` uses
// file:symbol (or file:line where the rule is an inline condition); "vicdata:" means the
// sibling ingest repo /Users/guy/dev/vicdata, where the RPCs and rollups live.
//
// `lift` marks S0's "must lift" rules -- enforced only in a component or the client page
// before 0.6. `lifted` stays false until the S2 lift reports the move (and that no figure
// changed). `testCase.check` names a runner in scripts/catalogue-rule-tests.ts.
import type { Rule, RuleId } from "./types";

const P = "src/app/teacher/[phase]/page.tsx";
const CP = "src/components/teacher/CandidatesPanels.tsx";
const SP = "src/components/teacher/SubjectPanels.tsx";
const XP = "src/components/teacher/ComparisonsPanels.tsx";
const GP = "src/components/teacher/GradeCountsPanels.tsx";
const SV = "src/components/teacher/SeriesViews.tsx";
const TVP = "src/lib/teacher-view-panels.ts";
const SG = "src/lib/subject-grades.ts";
const QB = "src/lib/dfe-qualification-buckets.ts";
const CSER = "src/lib/teacher-view-comparator-series.ts";

export const RULES: Rule[] = [
  // ------------------------------------------------------------------ the twelve
  {
    id: "R-ENTRIES-NOT-POINTS",
    statement:
      "Entries count every qualification; points come only from qualifications with a real challenge table, and a row with no points of its own shows none rather than borrowing another's.",
    why: "At GCSE, headline rows are per subject, so a BTEC or OCR item in the same subject showed the GCSE score as its own.",
    appliesTo: "M-KS4-ENTRIES, M-KS4-POINTS, M-KS5-ENTRIES, M-KS5-POINTS; every column",
    enforcedIn: [
      "vicdata:ingest/academic_aggregates.py:139-142,283-288 (entries_total from every TOTAL row; points only when qualification == points_qual)",
      "vicdata:supabase/migrations/20260915100000_academic_subject_rollup.sql:31,64-65 (avg_point_score, points_coverage_percent)",
      `${P}:pointsAt (936)`,
      `${P}:resultsFor (499)`,
    ],
    testCase: {
      urn: "137625",
      school: "The Chase",
      phase: "ks4",
      expect: "A BTEC or Cambridge National item in a subject that also has GCSE shows no Results figure (no specific item recorded yet).",
    },
    origin: "Academic Results phase build report; page gate from Teacher view round 6 (comment page.tsx:478-482)",
    status: "active",
    lift: {from: `${P}:pointsAt, resultsFor`, to: "src/lib/teacher-view-measures.ts:ownHeadlineRows, carriesOwnPoints, subjectPointsAt, subjectEntriesAt", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-POINTS-SAME-QUAL",
    statement:
      "A points figure is only comparable within one qualification type (KS4: qualification type; KS5: bucket or exact qualification). Post-16 Context on points keeps to the focused item's qualification family on every group, All subjects included; a figure that could only be a blend is not shown.",
    why: "A-level, BTEC and IB points sit on different challenge tables; one bar chart or average across them compares unlike scales.",
    appliesTo: "M-KS4-POINTS, M-KS5-POINTS; map chips, Column 1 category, Context",
    enforcedIn: [
      "src/lib/teacher-view-catalogue.ts:comparabilityKey (124-127)",
      "src/app/api/teacher/dashboard/route.ts:englandAverages (56-72, exact qualification)",
      `${P}:candidateItems (1063-1099, via R-QUAL-FAMILY-MATCH)`,
      "src/lib/teacher-view-measures.ts:contextKeepsToFamily, onFocusPointsScale, contextGroupValue (Post-16 points rows in the focus's family only)",
      "src/lib/teacher-view-populations.ts:contextItemsOf (keepToFamily: All subjects on Post-16 points)",
    ],
    testCase: {
      urn: "130432",
      school: "Croydon College",
      phase: "ks5",
      subject: "Business Studies",
      year: "2024/25",
      expect:
        "Context on Average point score: Business Studies (A level + five BTEC sizes) has one group value per family -- the A-level family's is the A-level row's own 26.36, the BTEC family's is the BTEC rows' weighted mean; no focus = no value. With A-level Computer Science focused, All subjects draws 20 A-level subjects (was 55 across every family) and its average is 25.6 (was a 24.7 blend).",
      check: "pointsSameQual",
    },
    origin: "Academic Results phase; Post-16 Part C and Part D",
    status: "active",
    lift: {from: `${P}:groupValueFor (1207-1216), contextItems (1361-1369)`, to: "src/lib/teacher-view-measures.ts:subjectPointsAt, latestOwnPoints; POINTS_BEARING_QUALIFICATION -> src/lib/dfe-qualification-buckets.ts", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
    fixes: [
      "S3b (Guy's decision 3, 3 Oct 2026): Post-16 Context on points no longer blends A level, BTEC and IB. contextGroupValue keeps each member's rows to the focused item's qualification family (display bucket), and contextItemsOf keeps All subjects' peers to it too (contextKeepsToFamily = Post-16 points; entries still add up across families). A row with no qualification type is never counted (suppressed, not blended); none occurred in the real data checked. The Context note says 'Points are on a different scale for each qualification type, so only <family> subjects are compared.' Before/after for 130432, 117037, 100369 and 130448 in the commit message.",
    ],
  },
  {
    id: "R-KS4-POINTS-GCSE-FULL",
    statement: "KS4 points come only from GCSE (9-1) Full Course entries with a clean single grade.",
    why: "Short courses, Double Award and vocational qualifications have no place on the 9-1 points table; scoring them would invent figures.",
    appliesTo: "M-KS4-POINTS; Column 1 geography (applicability)",
    enforcedIn: [
      "vicdata:ingest/academic_aggregates.py:139-140,285 (grade in points_table = single grades only)",
      "src/components/data-view/SubjectAreaSection.tsx:POINTS_BEARING_QUALIFICATION (151-155), imported by page.tsx:34",
      `${P}:pointsAt (936), resultsFor (499)`,
      `${P}:geography applies (1729, 1857)`,
    ],
    testCase: {
      urn: "137625",
      school: "The Chase",
      phase: "ks4",
      expect: "A subject offered as both GCSE and Cambridge National: only the GCSE item carries a points figure (item TBD).",
    },
    origin: "Academic Results phase (GCSE points); Teacher view round 6",
    status: "active",
    lift: {from: "src/components/data-view/SubjectAreaSection.tsx:POINTS_BEARING_QUALIFICATION; page.tsx gates", to: "src/lib/teacher-view-measures.ts:carriesOwnPoints", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-KS5-ASAEA-EXCL",
    statement:
      "AS level and AEA are left out of comparison lists, group totals and averages at Post-16, never out of the focused item's own figure -- and a focused AS/AEA item counts itself into its own group.",
    why: "AS entries double-counted beside A level and inflated group totals: 102239's 'All subjects' total was 2,480 against 591 real non-AS entries.",
    appliesTo: "M-KS5-ENTRIES, M-KS5-POINTS, M-KS5-THRESHOLD, M-KS5-BANDS; Column 1 category, Context",
    enforcedIn: [
      `${QB}:isAsLevelOrAea (138-141)`,
      `${P}:comparablePeer (1055)`,
      `${P}:candidateItems (1075)`,
      `${P}:groupRows, inGroup (1190-1191)`,
      `${P}:threshold group (1228), asOrAeaOnly (1249-1253), selected (1265,1277,1282), band share (1331), contextItems (1367), schoolSubjects (1837)`,
    ],
    testCase: {
      urn: "102239",
      school: "Whitmore High School",
      phase: "ks5",
      year: "2024/25",
      expect: "Context 'All subjects' entries group total 591 (was 2,480 with AS/AEA and the doubled bucket rows).",
      check: "asAeaGroupTotal",
    },
    origin: "Post-16 Part C1 (..._post16_category_context_exclude_as_aea_build_report_v1.md); Part D",
    status: "active",
    lift: {from: `${P} (the population filters listed under enforcedIn)`, to: "src/lib/teacher-view-populations.ts:isComparablePeer, contextGroupRows; src/lib/teacher-view-measures.ts:contextGroupValue", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
    fixes: [
      "S3b (Guy's decision 3, Part D decision 1): a focused AS or AEA item counts itself into its own Context group. contextGroupRows and inContextGroup keep the focused item's own exact-qualification rows (headline and grade), and asOrAeaOnlySubjects no longer holds the focus's subject, so an AS-only focus is a member of All subjects and Selected, and its share and benchmark are of a group it is in. Every other AS/AEA row stays out. Applied to any AS/AEA focus, not only AS-only subjects (an AS Psychology focus beside A-level Psychology now adds its own AS entries too). Before/after (130432 Law and Economics AS, 130448 Further Maths AS, 100053 Psychology AS) in the commit message.",
    ],
  },
  {
    id: "R-KS5-ENGLAND-EXACT",
    statement: "The Post-16 England figure is the exact subject × qualification figure or nothing; there is no bucket fallback.",
    why: "A bucket average drawn beside an IB HL or VRQ bar compared the item with a figure for different qualifications.",
    appliesTo: "M-KS5-POINTS, M-KS5-ENTRIES (geography); Column 1 Results markers and geography views",
    enforcedIn: [
      "src/app/api/teacher/dashboard/route.ts:englandAverages (56-72)",
      `${P}:englandValue keying (521-538)`,
      "src/app/api/teacher/subject-geography/route.ts:61-64 (exact qualification at ks5)",
    ],
    testCase: {
      urn: "100369",
      school: "The Godolphin and Latymer School",
      phase: "ks5",
      subject: "Chemistry",
      year: "2024/25",
      expect: "Own IB HL 58.29; England exact: IB HL 43.13, IB SL 37.84 (Part D report :65).",
      check: "englandExact",
    },
    origin: "Post-16 Part C, Part D",
    status: "active",
  },
  {
    id: "R-MIN-SCHOOLS",
    statement:
      "An LA or region benchmark row is suppressed below 5 schools. England is exempt (minimum 1) for points and entries geography and the England anchor, but not for grade-grain geography, where every grade row needs 5 schools.",
    why: "A figure from one or two schools identifies them and swings wildly; it is not a benchmark.",
    appliesTo: "Every LA / region / England figure",
    enforcedIn: [
      "vicdata:supabase/migrations/20260926140000_subject_geography_lookup_min_school_count.sql:35,66,90,123",
      "vicdata:supabase/migrations/20260927121000_academic_subject_grade_geography_aggregate.sql:50,82",
      "src/app/api/teacher/subject-geography/route.ts:59 (national passes 1)",
      "src/app/api/teacher/dashboard/route.ts:66,74 (national passes 1)",
      "src/lib/vicdata-reference.ts:lookupAcademicSubjectGradeGeography (633, passes null)",
    ],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      year: "all years",
      expect: "Camden (the school's LA) GCSE points geography: every row returned by default has school_count >= 5, and asking for minimum 1 returns more rows.",
      check: "minSchools",
    },
    origin: "Subject geography rounds (min school count migration)",
    status: "active",
  },
  {
    id: "R-SINGLE-BUCKET-100",
    statement:
      "The unfiltered (Type = All) category view shows points only when the category's scoreable entries are 100% one scored bucket, and the comparator side agrees on the bucket. No tolerance band.",
    why: "A category mixing A level and BTEC has no single points scale; borrowing one bucket's points would misdescribe the rest.",
    appliesTo: "Data View category measures (not the Teacher view)",
    enforcedIn: ["src/components/data-view/SubjectAreaSection.tsx:singleScoredBucketFor, agreedScoredBucketFor (68-100)"],
    testCase: null,
    origin: "Data View subject area round",
    status: "active",
    lift: {
      from: "src/components/data-view/SubjectAreaSection.tsx:singleScoredBucketFor, agreedScoredBucketFor",
      to: "src/lib/academic-data-view.ts",
      lifted: false,
      note: "Deferred: needed only when Data View category measures are registered. No Teacher view path uses it.",
    },
  },
  {
    id: "R-IB-NONSUBJECT",
    statement:
      "Baccalaureate (Diploma total, Combined Certificate) and IB Core rows are excluded from subject entries; IB Core components are included in IB bucket points; the Diploma total is never scored.",
    why: "Including the Diploma total pushed 100369's IB average to 60.2, above the HL maximum of 60.",
    appliesTo: "M-KS5-ENTRIES, M-KS5-POINTS",
    enforcedIn: [
      "vicdata:ingest/academic_aggregates.py:_NON_SUBJECT_ROWS (103-135), skip (270), points kept (446-455)",
      "vicdata:supabase/migrations/20260918160000_remove_ib_non_subject_rows.sql",
      `${QB}:challengeFor (246-262, the TS twin)`,
      `${QB}:NON_SUBJECT_ROWS, isNonSubjectRow (the port of _NON_SUBJECT_ROWS, S3b)`,
      "src/lib/teacher-view-populations.ts:subjectItemsOf (the Teacher subject list, S3b)",
    ],
    testCase: {
      urn: "118952",
      school: "Sevenoaks School",
      phase: "ks5",
      year: "2024/25",
      expect: "The exact-qualification rollup has no Baccalaureate / IB Core subject rows, and the Teacher view's subject list (subjectItemsOf over the raw facts) carries none either: 29 items in 2024/25, not 32. The raw facts themselves still carry Baccalaureate, Learning Skills and Study Skills (244 each).",
      check: "ibNonSubject",
    },
    origin: "IB ingest round (vicdata), Post-16 points",
    status: "active",
    fixes: [
      "S3b (Guy's decision 4, 3 Oct 2026): the Teacher subject list leaves them out. page.tsx:buildSubjectItems moved to src/lib/teacher-view-populations.ts:subjectItemsOf, which drops every raw-facts row isNonSubjectRow matches; NON_SUBJECT_ROWS is an exact port of vicdata ingest/academic_aggregates.py:_NON_SUBJECT_ROWS (one list, pointing at its source). Before the fix the picker DID show them at Sevenoaks (118952): 'Learning Skills', 'Study Skills' and 'Baccalaureate', 244 entries each, top of the IB tab and of the list (Learning Skills and Baccalaureate under 'Other subjects', Study Skills under 'Enterprise & Applied Studies'); also at Godolphin and Latymer (100369), 26 each. Before/after in the commit message.",
    ],
  },
  {
    id: "R-FOCUS-NEVER-FILTERED",
    statement:
      "The focused item (a subject, or the school itself in Comparisons) is never filtered out of its own figures, only out of comparison lists.",
    why: "Exclusion rules written for comparison populations would otherwise blank the very subject a teacher picked (e.g. an AS Psychology focus).",
    appliesTo: "Every measure; Column 1, Context, Comparisons",
    enforcedIn: [
      `${P}:candidateItems (1068-1070, focus first)`,
      `${P}:1141, 1362, 1381 (r.key === focusKey ||), 1837`,
      `${XP}:254, 276 (s.isTarget ||)`,
      "src/lib/teacher-view-populations.ts:contextGroupRows, inContextGroup, asOrAeaOnlySubjects (the focused AS/AEA item's own rows count into its group, S3b)",
      `${CSER}:143 (target never dropped), 186 (target kept in fixed sets, flagged igcseExcluded)`,
    ],
    testCase: {
      urn: "102239",
      school: "Whitmore High School",
      phase: "ks5",
      subject: "Psychology (AS)",
      expect:
        "Focus an AS item (AS Psychology in the AS/AEA report :19,38, which named no school; 102239 is a heavy-AS school): its own Column 1 panels still render with its own figures.",
    },
    origin: "Post-16 Part C1 (AS/AEA); content round S4",
    status: "active",
    lift: {from: `${P} (focus-first population code); ${XP}:254,276`, to: "src/lib/teacher-view-populations.ts:keepFocusOrFigured; src/lib/teacher-view-comparisons.ts:comparisonSchools", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
    fixes: ["S3b (Guy's decision 3, Part D decision 1): a focused AS or AEA item counts itself into its own Context group. contextGroupRows and inContextGroup keep the focused item's own exact-qualification rows (headline and grade), and asOrAeaOnlySubjects no longer holds the focus's subject, so an AS-only focus is a member of All subjects and Selected, and its share and benchmark are of a group it is in. Every other AS/AEA row stays out. Applied to any AS/AEA focus, not only AS-only subjects (an AS Psychology focus beside A-level Psychology now adds its own AS entries too). Before/after (130432 Law and Economics AS, 130448 Further Maths AS, 100053 Psychology AS) in the commit message."],
  },
  {
    id: "R-TREND-3YR",
    statement: "Trend views need 3+ years; below that, show the table only.",
    why: "Superseded: the live threshold for a line is 4 real years (R-TREND-LINE-4YR). TREND_MIN_YEARS = 3 survives only in the round-5 axis catalogue used by /teacher/meetings.",
    appliesTo: "Trend views",
    enforcedIn: ["src/lib/teacher-view-catalogue.ts:TREND_MIN_YEARS (24), used by src/app/teacher/meetings/page.tsx:25,69,76,153"],
    testCase: null,
    origin: "Teacher view round 5 (axis catalogue)",
    status: "superseded",
    supersededBy: "R-TREND-LINE-4YR",
  },
  {
    id: "R-ZERO-CANDIDATE",
    statement:
      "A school with a stage row but no real candidate count and no real headline measure is not 'present' for that stage; special schools are matched only with special schools (and vice versa) in nearest and comparator pools.",
    why: "Ark Soane (candidates = 0) appeared in every Data View list; Haverstock was matched with special schools.",
    appliesTo: "Comparator populations (Data View, dashboard card, nearest / comparator RPCs)",
    enforcedIn: [
      "src/lib/academic-data-view.ts:stagesPresent (174-190) -- Data View and dashboard card",
      "supabase/migrations/20260930120000_nearest_schools_special_and_through_school.sql",
      "supabase/migrations/20261001120000_comparator_candidates_special_schools.sql:50-67",
    ],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      expect: "Ark Soane (candidates = 0) drops out of every Data View list; Harmood (special) gets 29/30 special comparators, Haverstock 0/30 (special_schools_zero_candidate report :24,34-35).",
    },
    origin: "Special schools / zero-candidate filtering round",
    status: "active",
    openIssue:
      "Not applied to Teacher view comparator sets (rankFixedSets): a zero-candidate comparator with a 0-valued entries point is not excluded in Comparisons. Consider applying stagesPresent there.",
  },
  {
    id: "R-POINTS-WEIGHTED",
    statement: "A subject's points across several qualifications in one family are weighted by points-eligible entries, not flat-averaged.",
    why: "A flat mean of the 'all' row and each bucket row let one IB entry count as much as forty A-level ones.",
    appliesTo: "M-KS5-POINTS (Context group values); rollups",
    enforcedIn: [`${P}:groupValueFor (1207-1216)`, "vicdata:ingest/academic_aggregates.py:285-288"],
    testCase: {
      urn: "130432",
      school: "Croydon College",
      phase: "ks5",
      subject: "Computer Science",
      year: "2024/25",
      expect: "On the A-level family's scale: Computer Science 7.0 (was 13.1), Chemistry 24.3 (was 29.7) (Part D report :57). Both are A-level-only in 2024/25 (Chemistry's AS row is excluded), so S3b's family filter leaves them unchanged.",
      check: "pointsWeighted",
    },
    origin: "Post-16 Part D",
    status: "active",
    lift: {from: `${P}:groupValueFor`, to: "src/lib/teacher-view-measures.ts:contextGroupValue", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },

  // ------------------------------------------------------------------ found by S0
  {
    id: "R-TREND-LINE-4YR",
    statement:
      "A trend is drawn as a line only with 4 or more real years; below that: per-year bars (TrendChart), a ranked change-in-units list (MultiTrend), or the table alone (Comparisons Trend); the Actual and Trend-line toggles disable.",
    why: "Two or three points drawn as a line read as a trend that isn't there.",
    appliesTo: "Every over-time view",
    enforcedIn: [
      `${TVP}:TREND_LINE_MIN_YEARS, trendChartKind (311-315)`,
      `${SV}:multiTrendHasLine (48-49), MultiTrend fallback (76-90)`,
      "src/components/teacher/TrendChart.tsx:185",
      `${XP}:614-616, 649 (table only)`,
      `${CP}:284, 292`,
      `${SP}:789, 798`,
    ],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      subject: "Maths (General)",
      expect: "Average points has 4 real years (2021/22-2024/25) -> line; Grade 4+ has 4 too since 0.6.2 (2021/22-2024/25) -> line (it had 2, 2023/24-2024/25 -> bars / change list, before).",
      check: "trendLine",
    },
    origin: "Teacher view round 7 §4",
    status: "active",
    openIssue: "Legacy TREND_MIN_YEARS = 3 (teacher-view-catalogue.ts:24) is still read by /teacher/meetings: retire it or document it.",
  },
  {
    id: "R-DONUT-COUNTS-ONLY",
    statement: "Share (donut) only for counts (entries), and for grade bands once a range is picked; never for averages or rates.",
    why: "A share of an average point score is not a meaningful percentage.",
    appliesTo: "DV-C2-CUR-DONUT; M-*-ENTRIES, M-*-BANDS",
    enforcedIn: [`${P}:1956`, `${SP}:297 (fallback to bar), 525-534 (button disabled)`, "src/components/teacher/ShareDonut.tsx:10 (comment)"],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      expect: "Context on Results, Average points: the Share (donut) button is disabled ('Share is only meaningful for candidate numbers').",
    },
    origin: "Teacher view round 6 §4.2",
    status: "active",
    lift: {from: `${P}:1956; ${SP}:297, 525-534`, to: "src/lib/teacher-view-measures.ts:shareApplies", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-NO-GRADE-RATE-GEO",
    statement:
      "No LA, region or England benchmark for the Grade 4+ / A*-E rate; the geography comparison is points-only on Results (entries on Candidates).",
    why: "No area threshold figure is wired up; drawing one from another measure would compare unlike things.",
    appliesTo: "M-KS4-THRESHOLD, M-KS5-THRESHOLD; Column 1 Results markers and geography views",
    enforcedIn: [`${P}:1136 (no benchmark on rates)`, `${P}:1153 (no England category line)`, `${P}:1727-1734 (applies)`, `${P}:1786 (benchmarkLabel undefined)`],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      expect: "Results -> Grade 4+ -> Area chart shows 'LA, regional and national figures are published for average point score only…'.",
    },
    origin: "Comparisons / Grade 4 wiring round",
    status: "active",
    lift: {from: `${P}:1136, 1153, 1727-1734, 1786`, to: "src/lib/teacher-view-measures.ts:hasEnglandPointsBenchmark", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
    openIssue:
      "Audit B: the grade geography (academic_subject_grade_geography_aggregate, 2021-2024) would give an England Grade 4+ rate (the 9-4 band), so the gap is wiring, not data.",
  },
  {
    id: "R-BANDS-ENGLAND-BENCH",
    statement: "On Grade bands the focused subject's benchmark is England's rate on the same span, from grade geography; peers carry none.",
    why: "A band rate is only comparable with the same band computed the same way on England's own grade rows.",
    appliesTo: "M-KS4-BANDS, M-KS5-BANDS; Column 1 Results tiles and Grades view",
    enforcedIn: [`${SP}:282-292`],
    testCase: {
      urn: "137625",
      school: "The Chase",
      phase: "ks4",
      subject: "History",
      year: "2024/25",
      expect: "Grades 7-9: 34.1% (45 of 132) vs England 26.6% (76,171 of 286,338); grades 4-9: 75.8% vs 64.6% (grade bands report :60).",
      check: "bandsEnglandBench",
    },
    origin: "Grade bands frontend round",
    status: "active",
    lift: {from: `${SP}:282-292`, to: "src/lib/teacher-view-grade-geography.ts:withEnglandBandBenchmark", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-GRADE-SCALE-MATCH",
    statement:
      "A rate is computed only on the scale it was defined on (threshold: GCSE 9-1 / Double Award at KS4, A-level A*-E at KS5; bands: the scale the range was picked on). Vocational, IB and Pre-U rows get no figure.",
    why: "An IB 7-1 row read as GCSE numerics would be scored against a grade 4 it was never on.",
    appliesTo: "M-*-THRESHOLD, M-*-BANDS",
    enforcedIn: [`${SG}:thresholdRate (155-180)`, `${SG}:bandRate (232-241)`, `${SG}:BAND_PRESETS (201-205)`],
    testCase: {
      urn: "137625",
      school: "The Chase",
      phase: "ks4",
      expect: "Asked for GCSE 7-9, a BTEC returns no figure (not 0%); an IB 7-1 row at KS5 is not scored against grade 4.",
    },
    origin: "Teacher view round 6 §6.5; grade bands round",
    status: "active",
  },
  {
    id: "R-NON-GRADES-EXCL",
    statement: "Suppressed, No result, X, Covid impacted and other non-grades (2021/22-2022/23 KS5 too: COVID result, Supp) are excluded from both sides of every grade rate and distribution.",
    why: "Counting them in the denominator depresses a real rate by however much DfE chose not to publish.",
    appliesTo: "M-*-THRESHOLD, M-*-BANDS, M-*-COUNTS",
    enforcedIn: [`${SG}:NON_GRADE_VALUES (88), thresholdRate (160), bandRate (248)`, `${GP}:56, 86`, `${SP}:456-457`],
    testCase: null,
    origin: "Teacher view round 6 §6.5",
    status: "active",
  },
  {
    id: "R-THRESHOLD-PERIODS",
    statement: "Grade-based measures cover 2021/22 on at school level (0.6.2; 2023/24 on before); the axis is shortened to the years a subject has grades, never padded.",
    why: "School grade rows begin in 2021/22 (the rollup or the historic facts; 2020/21 has no grades); padding earlier years would draw empty or borrowed values.",
    appliesTo: "M-*-THRESHOLD, M-*-BANDS, M-*-COUNTS",
    enforcedIn: [`${P}:1112-1116, 1315-1320`],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      expect: "The school's grade rows cover exactly 2021/22-2024/25 (0.6.2; 2023/24 and 2024/25 before), so Results on Grade 4+ shows 4 years.",
      check: "thresholdPeriods",
    },
    origin: "Teacher view round 6 §6.5",
    status: "active",
    lift: {from: `${P}:1112-1116, 1315-1320`, to: "src/lib/teacher-view-measures.ts:periodsForMeasure", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
    fixes: [
      "0.6.2 S2: school grade rows read 2021/22-2024/25 (src/lib/grade-rows.ts; academic-data-view.ts:fetchSubjectLevelDataForSchools gradeYears \"four\"): the rollup at KS4 through academic_subject_grade_rollup_lookup once applied, else the modern + historic facts; the facts at KS5. Grade measures gain 2021/22-2022/23 (docs/v0.6/grade_rollup_reconciliation_v1.md).",
    ],
  },
  {
    id: "R-HISTORIC-GRADE-LABELS",
    statement:
      "2021/22-2022/23 KS5 grade labels are read in their 2023/24 words: vocational short codes (* D M P HM HP, ** *D DD DM MM MP PP, *** **D *DD DDD DDM DMM MMM MMP MPP PPP) become Distinction* ... Pass-Pass-Pass on BTEC, OCR Cambridge Technical, Other General Qualification and AEA, and on a VRQ set only where it carries a code no A-level-type scale has; never on A level, AS, EPQ, Core Maths, FSMQ, IB or Pre-U. COVID result and Supp are non-grades (R-NON-GRADES-EXCL). KS4's historic labels already match.",
    why: "'*' and 'D' are A-level grades too: read raw, a 2021/22 BTEC lands on the A-level scale, its bands give no figure and Grade counts shows letters; an unmapped COVID result left about 9% of 2021/22 A-level sets with no A*-E figure.",
    appliesTo: "M-KS5-THRESHOLD, M-KS5-BANDS, M-KS5-COUNTS (2021/22-2022/23)",
    enforcedIn: ["src/lib/grade-rows.ts:mapHistoricKs5Grade, parseSubjectGradeDistribution", `${SG}:NON_GRADE_VALUES (88)`],
    testCase: {
      urn: "130432",
      school: "Croydon College",
      phase: "ks5",
      subject: "Business Studies (BTEC Extended Certificate)",
      year: "2021/22",
      expect: "2021/22 reads Distinction* 2, Distinction 9, Merit 31, Pass 9 on the vocational scale (no '*' or 'D' rows, COVID result 44 a non-grade); King's Worcester (117037) A-level Maths 2021/22 keeps its '*' rows on the A-level scale, A*-E 100% of 45.",
      check: "historicGradeLabels",
    },
    origin: "0.6.2 S1 §4 (docs/v0.6/grade_rollup_reconciliation_v1.md); S2",
    status: "active",
  },
  {
    id: "R-QUAL-FAMILY-MATCH",
    statement:
      "Column 1's category and Context's Selected set contain only the focus's qualification family (KS5 display bucket). 'All subjects' crosses families, except on Post-16 points, where it keeps to the focus's family too (R-POINTS-SAME-QUAL).",
    why: "Core Maths beside A-level Maths in one category compared unlike qualifications.",
    appliesTo: "Column 1 category, Context Selected",
    enforcedIn: [`${P}:1063-1065, 1076, 1261-1263, 1272, 1277, 1282`],
    testCase: {
      urn: "137625",
      school: "The Chase",
      phase: "ks5",
      subject: "Mathematics (A level)",
      expect: "A-level Maths focus: 5 bars, Core Maths absent (qualification-match report :29).",
    },
    origin: "Column 1 qualification match round; combined round §4c",
    status: "active",
    lift: {from: `${P}:1063-1065, 1076, 1261-1283`, to: "src/lib/teacher-view-populations.ts:focusQualificationFamily, categoryItemsOf, contextMembersOf", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
    fixes: ["S3b: on Post-16 points 'All subjects' keeps to the focus's qualification family (R-POINTS-SAME-QUAL). On entries and rates it still crosses families: counts add up, and rates are scored only on their own grade scale."],
  },
  {
    id: "R-KS4-SUBJECT-DEDUP",
    statement: "At GCSE, one category row per subject (headline rows are per subject); at Post-16, none.",
    why: "GCSE headline rows are per subject, so two qualification items in one subject would repeat the same figure.",
    appliesTo: "M-KS4-*; Column 1 category",
    enforcedIn: [`${P}:1096-1099, 1839`],
    testCase: null,
    origin: "Trend redesign step 1",
    status: "active",
    lift: {from: `${P}:1096-1099, 1839`, to: "src/lib/teacher-view-populations.ts:candidateItemsOf", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-SELF-INCLUSIVE-GROUP",
    statement: "Group totals and averages include the focused subject.",
    why: "Before the fix a share could pass 100% (snagging round 1 Part 1).",
    appliesTo: "Context group, Column 1 category",
    enforcedIn: [`${P}:1152, 1270-1285 (esp. 1277)`, `${CP}:157-160`],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      expect: "No Context donut share exceeds 100%.",
    },
    origin: "Teacher view round 6 §4.2; snagging round 1 Part 1",
    status: "active",
    lift: {from: `${P}:1152, 1270-1285; ${CP}:157-160`, to: "src/lib/teacher-view-populations.ts:contextMembersOf, inContextGroup", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
    fixes: ["S3b (Guy's decision 3, Part D decision 1): a focused AS or AEA item counts itself into its own Context group. contextGroupRows and inContextGroup keep the focused item's own exact-qualification rows (headline and grade), and asOrAeaOnlySubjects no longer holds the focus's subject, so an AS-only focus is a member of All subjects and Selected, and its share and benchmark are of a group it is in. Every other AS/AEA row stays out. Applied to any AS/AEA focus, not only AS-only subjects (an AS Psychology focus beside A-level Psychology now adds its own AS entries too). Before/after (130432 Law and Economics AS, 130448 Further Maths AS, 100053 Psychology AS) in the commit message."],
  },
  {
    id: "R-SAME-YEAR-BENCH",
    statement: "A benchmark is read for the same year as the figure, or not at all.",
    why: "A latest-year figure beside an older England figure reads as a gap that is partly just time.",
    appliesTo: "Every benchmark marker and gap tile",
    enforcedIn: [`${P}:531-538, 963`, `${SP}:342`],
    testCase: null,
    origin: "Teacher view design brief §6, §14",
    status: "active",
    lift: {from: `${P}:531-538, 963; ${SP}:342`, to: "src/lib/teacher-view-measures.ts:englandIndexOf, englandValueAt", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-PREV-YEAR-FALLBACK",
    statement: "With no benchmark, the delta is against the subject's own previous published year ('vs last year').",
    why: "A delta column with nothing to compare against would be blank for every rate.",
    appliesTo: "DV-C1-RES-CUR-TABLE",
    enforcedIn: [`${SP}:326-345, 643`],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      expect: "Results on Grade 4+, Sortable table: the delta column is headed 'vs last year'.",
    },
    origin: "Teacher view round 6",
    status: "active",
    lift: {from: `${SP}:326-345`, to: "src/lib/teacher-view-panels.ts:currentRowsWithDelta", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-MEASURE-FALLBACK",
    statement:
      "Context falls back to points when Results is on Grade bands without a range (or on Grade counts with no focused subject); Comparisons falls back to points (with a subject chip) or the headline (without). Since 0.6.3, Grade counts with a focused subject never falls back: it follows the selected grade, or prompts for one (R-COUNTS-SELECTION).",
    why: "Grade bands has no single figure to compare subjects or schools on until a range is picked.",
    appliesTo: "Context, Comparisons on Results",
    enforcedIn: [`${P}:1174-1175, 1436-1443`],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      expect: "Results -> Grade bands with no range saved: Context shows Average points with the note 'Pick a grade range from Grades ▾…'. Results -> Grade counts with nothing selected: Context and Comparisons show the prompt 'Click a grade in Results to compare it…', never points.",
    },
    origin: "Grade bands frontend round",
    status: "active",
    lift: {from: `${P}:1174-1175, 1436-1443`, to: "src/lib/teacher-view-measures.ts:contextFallsBackFor, contextMeasureFor, comparisonsMeasureFor", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-COUNTS-SELECTION",
    statement:
      "On Grade counts, a click on a grade in Column 1's Current selects it; a click on a second grade widens to the range between them; a third click starts a new selection; Clear, or a click on the single selected grade, removes it. The selection IS the band:range setting (the top bar's Grades ▾, same key and format). Context and Comparisons follow it as that range's share of graded entries (bandRate, comparator grade rows), titled 'Share at grade 9, by subject / by school (set)' with a 'Grade 9 · from your highlight' chip back to Column 1. Before any selection both columns show a prompt, not average points.",
    why: "Grade counts has no single figure to compare on, and a silent switch to points answered a different question from the one on screen.",
    appliesTo: "DV-C1-RES-CUR (Grade counts), Context and Comparisons on Grade counts, the top bar's Grades ▾",
    enforcedIn: [
      "src/lib/grade-selection.ts:nextSelection, savedSelection, answerLine, selectionChipLabel",
      "src/components/teacher/GradeCountsPanels.tsx (selection, answer line)",
      "src/components/dashboard-config/TeacherDashboard.tsx:countsRange, countsSelectionMeasure, selectionRateOf, countsPrompt",
      "src/components/teacher/SelectionBits.tsx; SubjectPanels.tsx / ComparisonsPanels.tsx (prompt, chip, titleLead); src/lib/view-series/frames.ts:comparisonsLeadTitle",
    ],
    testCase: {
      urn: "137625",
      school: "The Chase",
      phase: "ks4",
      subject: "History",
      year: "2024/25",
      expect: "Grade counts, click 9: the answer line reads 'Grade 9: N% of entries (n) · England E%' from the school's and England's own grade rows; click 7: 'Grades 7–9: 34% … · England 27%', the same figures as Grade bands 7–9 (R-BANDS-ENGLAND-BENCH).",
      check: "countsSelection",
    },
    origin: "0.6.3 grade counts, maps, tables round (S1)",
    status: "active",
  },
  {
    id: "R-RANGE-ENDS-GRADED",
    statement: "U, Fail and Unclassified (and non-grades, '*' and grades off the subject's scale) can't start or end a range: clicking them in Grade counts does nothing, and their tooltip says why. Both phases.",
    why: "A range runs between graded results; the top bar's picker already hides these (pickableGrades).",
    appliesTo: "DV-C1-RES-CUR (Grade counts)",
    enforcedIn: ["src/lib/grade-selection.ts:rangeEndGrade, notRangeEndReason", "src/components/teacher/GradeDistribution.tsx (clickable, clickTitle)"],
    testCase: null,
    origin: "0.6.3 grade counts, maps, tables round (S1)",
    status: "active",
  },
  {
    id: "R-ENGLAND-GRADED-ONLY",
    statement: "England's share inside a grade selection is over graded, non-suppressed rows only. Where England suppresses a grade, or doesn't publish one the school's spread draws, the figure is partial and is not shown.",
    why: "A share of a smaller total than the school's would overstate or understate England beside the school's own share.",
    appliesTo: "DV-C1-RES-CUR (Grade counts answer line)",
    enforcedIn: ["src/lib/grade-selection.ts:englandShare, answerLine"],
    testCase: null,
    origin: "0.6.3 grade counts, maps, tables round (S1, S3)",
    status: "active",
  },
  {
    id: "R-MIN-ENTRIES",
    statement: "A selection's share at one subject (Context) or one school (Comparisons) needs at least MINIMUM_SUBJECT_N (5) graded entries, the Data View's small-entries rule; below it the subject or school reads 'too few entries', not a %.",
    why: "A share of one or two entries swings by tens of points and ranks noise.",
    appliesTo: "Context and Comparisons on a Grade counts selection",
    enforcedIn: [
      "src/lib/academic-data-view.ts:MINIMUM_SUBJECT_N",
      "src/components/dashboard-config/TeacherDashboard.tsx:selectionRateOf",
      "src/components/teacher/ComparisonsPanels.tsx:tooFewUrns; src/lib/view-series/ranking.ts:schoolRanking (tooFew)",
    ],
    testCase: null,
    origin: "0.6.3 grade counts, maps, tables round (S1)",
    status: "active",
  },
  {
    id: "R-GEO-APPLIES",
    statement:
      "The geography comparison is shown only where the area figure counts the same thing: at KS4 for GCSE (9-1) Full Course items only; on Results for points only.",
    why: "Area entries count points-eligible GCSE entries only; set beside a BTEC item they would compare different things.",
    appliesTo: "DV-C1-*-TR-GEO-*",
    enforcedIn: [`${P}:1727-1734, 1857`],
    testCase: {
      urn: "137625",
      school: "The Chase",
      phase: "ks4",
      expect: "A GCSE BTEC focus shows the not-applicable note on Area chart.",
    },
    origin: "Candidates live review Part 5; Post-16 Part C",
    status: "active",
    lift: {from: `${P}:1727-1734, 1857`, to: "src/lib/teacher-view-geography.ts:candidatesGeographyApplies, resultsGeographyApplies", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-GEO-POINTS-ELIGIBLE",
    statement: "The school's own row beside area entries is its points-eligible entries (entries × coverage), not its Candidates count.",
    why: "Area entries are points-eligible entries; the school's full count beside them would overstate its share.",
    appliesTo: "DV-C1-CAND-TR-GEO-*",
    enforcedIn: [`${P}:1859-1862`, `${CP}:370-371 (caveat)`],
    testCase: null,
    origin: "Candidates live review Part 5",
    status: "active",
    lift: {from: `${P}:1859-1862`, to: "src/lib/teacher-view-geography.ts:pointsEligibleEntriesByPeriod", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-IGCSE-EXCL",
    statement:
      "At GCSE a comparator flagged by igcseExclusionLikely is dropped from every set; the target is kept but flagged and its results history withheld.",
    why: "Schools sitting IGCSEs show artificially low DfE GCSE figures; ranking them against GCSE schools misleads.",
    appliesTo: "Comparisons (all GCSE measures); comparator maps",
    enforcedIn: [`${CSER}:130, 143, 159, 175, 186, 199`, "src/components/teacher/RankingsMap.tsx:90", "src/lib/academic-data-view.ts:igcseExclusionLikely (679)"],
    testCase: {
      urn: "117037",
      school: "The King's School Worcester",
      phase: "ks4",
      expect: "Malvern College / Malvern St James absent from the set (unconfirmed, content round report :152).",
    },
    origin: "Commit 514e285; content round S4",
    status: "active",
  },
  {
    id: "R-COMPARATOR-NO-FIGURE",
    statement:
      "A comparator with no figure for the measure (or none in the latest year) is not listed and never ranked last. Not applied while loading.",
    why: "'No data' placed last would let a school with nothing published appear to beat a genuinely low one, or look like a bottom score.",
    appliesTo: "Comparisons",
    enforcedIn: [`${XP}:254, 274-277`, `${TVP}:rankByValue (325-333)`],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks5",
      expect: "A school not offering the focus subject disappears from the set's bar chart and ranking (content round S4).",
    },
    origin: "Content round S4; round 7 §9",
    status: "active",
    lift: {from: `${XP}:254, 274-277`, to: "src/lib/teacher-view-comparisons.ts:comparisonSchools, rankedComparisons", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-COMPARATOR-RATE-PER-QUAL",
    statement: "Comparator rates are scored per subject and exact qualification, with the page's own rate function.",
    why: "Pooling a comparator's qualifications mixes grade scales (Maths (General) moved +5pp when fixed).",
    appliesTo: "Comparisons on Grade 4+ / A*-E / bands; since 0.6.2 S3 also a subject column's 'Add an average' across schools on them",
    enforcedIn: [`${XP}:199-207`, `${P}:2043-2053`, "src/components/dashboard-config/TeacherDashboard.tsx:setGradeRowsFor, schoolSetGradesOn"],
    testCase: null,
    origin: "Comparisons / Grade 4 wiring",
    status: "active",
    lift: {from: `${XP}:199-207; ${P}:2043-2053`, to: "src/lib/teacher-view-comparator-grades.ts:rateSeriesByUrn", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-COMPARATOR-GRADE-SHARE",
    statement:
      "Grade counts across schools (Column 1's grade spread, 'Add an average' across the 10 nearest / a saved set) is each grade's share of a school's graded entries, averaged (mean or median) over the set's other schools with graded entries that year, for the focused subject and exact qualification; drawn as ticks in place of England's, at the school's own scale in counts mode. Never a raw count, never weighted by entries.",
    why: "Schools differ in size: an average of raw counts would draw a big school's spread, not the set's.",
    appliesTo: "M-*-COUNTS (set)",
    enforcedIn: ["src/catalogue/honest.ts:compareHonest (set)", "src/lib/grade-spread.ts:setShares", "src/lib/view-series/grades.ts:compareOf, buildGrades, buildBandSpread"],
    testCase: null,
    origin: "0.6.2 S3 (prompt: 'Grade counts across schools should show a share (%), not raw counts')",
    status: "active",
  },
  {
    id: "R-2122-GRADING-NOTE",
    statement:
      "A grade or points view over time whose years include 2021/22 carried a note that 2021/22 was graded more generously, so some fall from it reflects grading. Superseded by R-TREND-FROM-2223 (Guy, 6 Oct 2026): trends are now measured from 2022/23, and the note says so.",
    why: "2021/22 (summer 2022) was Ofqual's transition year: grading set roughly midway between 2021 and 2019.",
    appliesTo: "M-*-POINTS, M-*-THRESHOLD, M-*-BANDS, M-*-COUNTS, Comparisons' headline: over-time views",
    enforcedIn: [],
    testCase: null,
    origin: "0.6.2 S4 (prompt: 'wherever a grade or points trend includes 2021/22, put a short footnote on the view')",
    status: "superseded",
    supersededBy: "R-TREND-FROM-2223",
  },
  {
    id: "R-TREND-FROM-2223",
    statement:
      "On a grade or points measure (Average points, Grade 4+ / A*-E, Grade bands, Grade counts, Comparisons' headline; never Candidates, never KS2), 2021/22 stays on the Trends' graphs and tables, but every trend statement is measured from 2022/23 (TREND_BASE_PERIOD): the direction word (R-TREND-FLAT-4PCT) and the trend sentence ('… since 2022/23'), the group / 'vs:' clause, every year table's Change column (Trend and % change tables, Results' area change table: the card's two year columns are then 2022/23 and the latest; fullscreen shows every year), a fitted Trend line, a short span's ranked change bars, ranked change lists, change and Trend maps, the % change half's summary and collapsed figure, and a slope from the span's first year. Grade counts' change table (two years) measures from 2022/23 at the earliest, its 'From' menu from there; its spread may still be compared with 2021/22. Line charts (Trend, Results' area chart) draw 2021/22 as a normal point. A 'From' year of 2022/23 or later is unchanged. A view whose drawn years include 2021/22 carries TREND_BASE_NOTE after its source: in the panel's 'i', and printed as text in fullscreen and in 'Print this graph'. Never on a latest-year view, on Candidates or at KS2. Indexed lines are entries only (R-INDEX-HEADCOUNTS), so unaffected.",
    why: "2021/22 (summer 2022) was the first year back to exams after the pandemic: Ofqual set grading roughly midway between 2021 and 2019, so a trend measured from it would make most schools look as if results had fallen.",
    appliesTo: "M-*-POINTS, M-*-THRESHOLD, M-*-BANDS, M-*-COUNTS, Comparisons' headline (Attainment 8, A level points per entry): over-time views",
    enforcedIn: [
      "src/catalogue/notes.ts:TREND_BASE_PERIOD, TREND_BASE_NOTE, trendBaseApplies, trendBaseFor, trendNoteFor, specYears",
      `${TVP}:PanelData.statementFrom, withTrendBase, statementSpan, countedValues`,
      `${SV}:MultiTrend (short span), YearTable (Change column, card columns)`,
      "src/components/teacher/TrendChart.tsx:fit",
      "src/components/teacher/ColumnPanels.tsx:withTrendNote (PanelRender.gradingYears)",
      `${SP}:trendFull, trendSpan, changeFull, changeSpan`,
      `${XP}:full, trendSpan, changeSpanData, changeTableSpan, trendMapSpan`,
      "src/components/teacher/GeographyComparison.tsx:GeographyView statementFrom",
      `${GP}:changeEarlier`,
      "src/lib/grade-spread.ts:gradeCounts (changeEarlier)",
      "src/lib/view-series/subjects.ts:trendData, changeData",
      "src/lib/view-series/comparisons.ts:series, changeDrawn, changeSpan",
      "src/lib/view-series/geography.ts:buildGeography (table statementFrom)",
      "src/lib/view-series/map.ts:changeMap",
      "src/lib/view-series/slope.ts:slopeYears",
    ],
    testCase: {
      urn: "137625",
      school: "The Chase",
      phase: "ks4",
      subject: "History",
      year: "2021/22-2024/25",
      expect: "Grade bands and Average points Trends draw 2021/22-2024/25 and carry the note; their sentence and direction word are measured 2022/23-2024/25 ('since 2022/23'); a Trend from 2023/24 and the latest year are unchanged; Candidates and KS2 never (src/lib/trend-base.test.ts and src/lib/grading-note.test.ts, on the real hosts).",
      check: "trendFrom2223",
    },
    origin: "0.6.2 S4b (Guy's decision B, 6 Oct 2026), replacing S4's R-2122-GRADING-NOTE",
    status: "active",
  },
  {
    id: "R-CURRENT-GRADES-FROM-2324",
    statement:
      "A latest-year view on a grade measure (Grade 4+ / A*-E, Grade bands, Grade counts; Results, Context and Comparisons' rate) reads the school's grade rows from 2023/24 on only: its subject (or school) list, its year menu, its 'vs last year' and an explicit earlier-year spread are exactly as before the rows reached back to 2021/22. A subject with grades only in 2021/22-2022/23 appears on the Trends alone.",
    why: "The grade rows' two older years are for the trends. Read by a latest-year view, they listed subjects with no current figure ('no published figure' rows) and let 'vs last year' reach back past a missing 2023/24 to 2022/23 -- latest-year figures this round must not change (S5).",
    appliesTo: "M-*-THRESHOLD, M-*-BANDS, M-*-COUNTS: latest-year views",
    enforcedIn: [
      `${TVP}:latestYearFrom, latestYearSeries`,
      `${SP}:currentSubjects, currentFrame`,
      `${XP}:currentFrom, currentFrame`,
      "src/lib/grade-spread.ts:gradeCounts (latest)",
      "src/lib/view-series/grades.ts:earlierCounts, buildGrades",
      "src/components/dashboard-config/TeacherDashboard.tsx:focusScale (the band scale, since S2)",
    ],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      expect: "On Grade 4+ the Current subject lists match the 2023/24-on rows (no Turkish 'no figure' row), and Latin's 'vs last year' is '—' (no 2023/24), not 2024/25 against 2022/23 (src/lib/trend-base.test.ts).",
      check: "currentGradesFrom2324",
    },
    origin: "0.6.2 S4b (Guy's decision A, 6 Oct 2026), after S5's first parity run",
    status: "active",
  },
  {
    id: "R-RANKING-SAMPLE",
    statement:
      "A national or regional ranking set is a sample: no map or change maps; rank and average come from the whole population on the ranking's own (headline) measure.",
    why: "A map of a sample of schools across England is not a local picture, and a rank within the sample is not the school's real rank.",
    appliesTo: "Comparisons with a ranking set",
    enforcedIn: [`${XP}:213, 287-297, 494-506, 615, 713`, "src/lib/chooser-sets.ts:46-61"],
    testCase: null,
    origin: "Snagging round 1 Part 4",
    status: "active",
    lift: {from: `${XP}:213, 287-297, 494-506, 615, 713`, to: "src/lib/teacher-view-comparisons.ts:comparisonsCurrentView, onRankingMeasure, sampleAllowsMap", lifted: true, note: "S2 lift, verbatim; 30,888 scenarios equal before and after (docs/v0.6/audit_scripts/lift_equality)" },
  },
  {
    id: "R-PERIOD-TRIM",
    statement: "Leading and trailing periods with no published value are trimmed (2020/21 points are null nationally).",
    why: "An empty first year would start every Results trend on a gap.",
    appliesTo: "Every over-time view",
    enforcedIn: [`${TVP}:trimToData (269-278)`, `${CP}:165`],
    testCase: {
      urn: "100053",
      school: "Acland Burghley School",
      phase: "ks4",
      expect: "Any Results trend starts 2021/22.",
    },
    origin: "Teacher view round 7 §7",
    status: "active",
  },
  {
    id: "R-INDEX-HEADCOUNTS",
    statement: "Only sum measures (entries) are indexed to 100; points and rates are drawn at real levels.",
    why: "An index of an average reads as a % change of an average, which misleads (catalogue §3).",
    appliesTo: "Indexed trend views",
    enforcedIn: ["src/lib/teacher-view-trend-styles.ts:shouldIndex (102-104)", `${SV}:92`, "src/components/teacher/GeographyComparison.tsx:159"],
    testCase: null,
    origin: "Trend redesign",
    status: "active",
  },
  {
    id: "R-RANK-TIES",
    statement: "Ties share a rank; the next rank skips; a null is unranked.",
    why: "Standard competition ranking; a missing figure is not a position.",
    appliesTo: "Every rank",
    enforcedIn: [`${TVP}:rankByValue (325-333)`],
    testCase: null,
    origin: "Teacher view round 7 §9",
    status: "active",
  },
  {
    id: "R-TREND-FLAT-4PCT",
    statement: "A trend is 'Broadly stable' within ±4%.",
    why: "Small year-to-year noise should not be called growth or decline.",
    appliesTo: "Trend summaries and direction flags",
    enforcedIn: [`${TVP}:classifyChange (353-360)`],
    testCase: null,
    origin: "Teacher view wireframe",
    status: "active",
    fixes: [
      "0.6.2 S4b: on a grade or points measure the word is measured from 2022/23 (R-TREND-FROM-2223), where the chart draws 2021/22.",
    ],
  },
  {
    id: "R-NUMBER-TYPE-HONESTY",
    statement:
      "A measure is shown only in its honest number types (catalogue §3): counts as totals, % change, share or index; averages as points and change in points; rates as rate and change in percentage points.",
    why: "A % change of an average or a rate misleads: 60% -> 66% is +6pp, not +10%.",
    appliesTo: "Every view on M-*-POINTS, M-*-THRESHOLD, M-*-BANDS, M-*-HEADLINE",
    enforcedIn: [
      "src/catalogue/measures.ts (numberTypes)",
      "src/catalogue/matching.ts (offer filter, via dataview supports.numberType)",
      `${TVP}:ChangeKind, Measure.changeKind, changeOf, formatChange, changeMagnitude, changeTitle, changeInTitle, trendSentence`,
      `${SV}:YearTable (Change column, ranked by the honest change)`,
      "src/components/teacher/ChangeChart.tsx (format, axis units)",
      `${SP}:change half (ChangeList, titles, summary, headline)`,
      `${XP}:change half (ChangeList, change map trend vs trend_absolute, titles, summary, headline)`,
    ],
    testCase: null,
    origin: "Catalogue doc §3; decision C3",
    status: "active",
    fixes: [
      "S3b (Guy's decision 3, 3 Oct 2026): % change is no longer offered on points or rates in the Teacher view. Measure.changeKind ('percent' for entries and grade counts, 'points' for average point score and the GCSE/Post-16 headline, 'pp' for Grade 4+ / A*-E, grade bands and KS2's expected standard) drives every change view through changeOf / formatChange: Context's and Comparisons' ranked change lists and change tables (YearTable ranks and sorts by the honest change and drops the % beneath on points and rates; the Results geography table shows the change in points alone), the classic ChangeChart, Comparisons' change map (points and rates colour by absolute change, trend_absolute, keyed 'Change', instead of the ±% scale), every title ('Change in points' / 'Change in percentage points', changeInTitle), the summaries ('risen 0.4 points', 'fallen 3 percentage points'), the collapsed headline figure and trendSentence's tail. Counts keep % change. Direction words (Growing / Broadly stable / Declining) still use R-TREND-FLAT-4PCT's ±4% relative band: only the number printed changed. Not changed: the Data View's own map 'Trends' toggle (AcademicMapView, growth %) that Column 1 Results' Trend map shows, which is shared with the Data View.",
    ],

  },

  // ------------------------------------------------------------------ Rolls and births (audit B)
  {
    id: "R-ROLLS-HEADCOUNT",
    statement: "Rolls are census headcounts, not FTE; part-time pupils count as one.",
    why: "Mixing headcount and FTE across schools or years changes a roll without any pupil moving.",
    appliesTo: "M-ROLLS",
    enforcedIn: ["src/lib/roll-data.ts:1-3, 33"],
    testCase: null,
    origin: "Rolls build (Data View)",
    status: "active",
  },
  {
    id: "R-ROLLS-MAINSTREAM-AGG",
    statement: "LA, region and England roll aggregates count mainstream schools only.",
    why: "A school's share of an area should be of the comparable (mainstream) roll.",
    appliesTo: "M-ROLLS (area geographies)",
    enforcedIn: ["src/components/dashboard/RollCard.tsx:86 (note)", "supabase/migrations/20260807112000_roll_aggregates.sql"],
    testCase: null,
    origin: "Rolls aggregates build",
    status: "active",
    openIssue: "roll_aggregates scope 'regional' means LA (a naming trap), and LA rolls exist for 2025 only, so there is no LA roll trend table (audit B).",
  },
  {
    id: "R-BIRTHS-FULL-WINDOW",
    statement: "The births trend is shown only when all five years (2021-2025) exist for the area; otherwise nothing.",
    why: "A partial births window would draw a trend from a gap.",
    appliesTo: "M-BIRTHS",
    enforcedIn: ["src/lib/population-trend-lookup.ts:BIRTHS_EARLIEST_YEAR, BIRTHS_LATEST_YEAR (89-90), lookupBirthsTrend (117)"],
    testCase: null,
    origin: "Population trend section (public school page)",
    status: "active",
  },
  {
    id: "R-BIRTHS-SHIRE-SUM",
    statement: "A shire county's births are the sum of its districts' births.",
    why: "ONS publishes births at district level (E07) for two-tier areas; the county the school's LA is has no row of its own.",
    appliesTo: "M-BIRTHS (LA)",
    enforcedIn: ["src/lib/population-trend-lookup.ts:SHIRE_COUNTY_DISTRICT_GSS_CODES (99)"],
    testCase: null,
    origin: "Population trend section (public school page)",
    status: "active",
  },
];

// Every ID a type-level template allows, checked at runtime by the unit tests.
export const RULE_IDS: RuleId[] = RULES.map((r) => r.id);
