// VicData 0.6.1 S2: the preset table in docs/v0.6/views_preset_table.md, generated from the
// code (viewspec.ts), so the doc and the presets can't drift. The doc keeps it between
// PRESET_TABLE_START and PRESET_TABLE_END; `npx -y tsx scripts/views-preset-table.ts --write`
// rewrites that block, and src/lib/viewspec.test.ts checks it is current.
import { DATAVIEWS } from "./dataviews";
import { TEACHER_DASHBOARDS } from "./dashboards/teacher";
import { VIEW_PRESETS, type ViewSpec, type ViewYears } from "./viewspec";

export const PRESET_TABLE_START = "<!-- preset-table:start (generated by scripts/views-preset-table.ts; do not edit by hand) -->";
export const PRESET_TABLE_END = "<!-- preset-table:end -->";

const cell = (s: string) => s.replace(/\|/g, "\\|");

function years(y: ViewYears): string {
  const base = "latest" in y ? "latest" : `from ${y.from}${y.rollOn ? ", rolls on" : ""}`;
  return y.memberPick ? `${base} (members pick)` : base;
}

function subject(s: ViewSpec["data"]["subject"]): string {
  return typeof s === "string" ? s : `fixed: ${s.fixed}`;
}

function rows(r: ViewSpec["data"]["rows"]): string {
  if (r === undefined) return "—";
  return typeof r === "string" ? r : `saved set ${r.savedSet}`;
}

function look(spec: ViewSpec): string {
  const entries = Object.entries(spec.view.look as Record<string, unknown>);
  if (!entries.length) return "—";
  return entries.map(([k, v]) => `${k}: ${Array.isArray(v) ? v.join("+") : typeof v === "object" ? JSON.stringify(v) : String(v)}`).join("; ");
}

// Which of the four Teacher dashboards place the preset ("GCSE C", "Post-16 R", ...).
function placedOn(id: string): string {
  const short = (d: (typeof TEACHER_DASHBOARDS)[number]) => `${d.colour.key === "ks4" ? "GCSE" : "Post-16"} ${d.id.endsWith("candidates") ? "C" : "R"}`;
  const on = TEACHER_DASHBOARDS.filter((d) => d.panels.some((p) => p.dataviews.some((v) => v.kind === "view" && v.dataview === id))).map(short);
  return on.length ? on.join(", ") : "none (draft)";
}

export function presetTableMarkdown(): string {
  const head = [
    "| # | Preset (dataview) | Rail label | View · look | Data: source · subject · per · rows · shown as · years | Results measures | Variants | Icon | Title | On |",
    "|---|---|---|---|---|---|---|---|---|---|",
  ];
  const body = DATAVIEWS.map((dv, i) => {
    const s = VIEW_PRESETS.get(dv.id)!;
    const d = s.data;
    const data = [
      d.source + (d.entries ? ` (${d.entries})` : ""),
      subject(d.subject),
      d.per,
      rows(d.rows),
      d.shownAs + (d.change ? ` (${d.change})` : ""),
      years(d.years),
    ].join(" · ");
    const variants = s.variants ? Object.entries(s.variants).map(([k, v]) => `${k}: ${(v as string[]).join("/")}`).join("; ") : "all";
    return `| ${i + 1} | \`${dv.id}\` | ${cell(dv.label)} | **${s.view.kind}** · ${cell(look(s))} | ${cell(data)} | ${s.resultsMeasures ? s.resultsMeasures.join("/") : "all"} | ${variants} | ${s.icon} | ${cell(s.title || "(none)")} | ${placedOn(dv.id)} |`;
  });
  return [PRESET_TABLE_START, "", ...head, ...body, "", PRESET_TABLE_END].join("\n");
}
