-- LA -> ONS region (dashboard rebuild, Shape card's "population trend in the area"
-- piece, deliberately deferred at the 2026-08-28 investigation until this crosswalk
-- existed -- see docs/OPEN_QUESTIONS.md). Region isn't derivable from the GSS code
-- itself (the E06/E07/E08/E09/E10 prefix encodes LA TYPE -- unitary/district/
-- metropolitan/London borough/county -- not region), so this is a second, genuinely
-- separate piece of reference data, added to the existing la_gss_crosswalk table
-- (same natural home as dfe_code/gss_code) rather than a new table.
--
-- Source: reasoned from England's own stable, low-churn 9-region administrative
-- structure (unchanged in substance since the 2009 regional boundaries, including the
-- 2019/2021/2023 LGR unitary reorganisations already reflected in la_gss_crosswalk's
-- own dfe_code rows), cross-checked against every real dfe_code/la_name/gss_code
-- triple already in this table (182 rows, zero missed, zero guessed for the 22 Welsh
-- W06 rows which correctly get no region at all) -- not fetched verbatim from a single
-- machine-readable government source (attempted directly first; Wikipedia's own
-- district-level tables summarise away the exact district->region detail needed).
-- Flagged here explicitly as a first pass worth an independent spot-check, same
-- discipline as every other provisional reference table in this project.
alter table public.la_gss_crosswalk add column region text;

update public.la_gss_crosswalk t
set region = v.region
from (values
    ('201', 'London'),
    ('202', 'London'),
    ('203', 'London'),
    ('204', 'London'),
    ('205', 'London'),
    ('206', 'London'),
    ('207', 'London'),
    ('208', 'London'),
    ('209', 'London'),
    ('210', 'London'),
    ('211', 'London'),
    ('212', 'London'),
    ('213', 'London'),
    ('301', 'London'),
    ('302', 'London'),
    ('303', 'London'),
    ('304', 'London'),
    ('305', 'London'),
    ('306', 'London'),
    ('307', 'London'),
    ('308', 'London'),
    ('309', 'London'),
    ('310', 'London'),
    ('311', 'London'),
    ('312', 'London'),
    ('313', 'London'),
    ('314', 'London'),
    ('315', 'London'),
    ('316', 'London'),
    ('317', 'London'),
    ('318', 'London'),
    ('319', 'London'),
    ('320', 'London'),
    ('330', 'West Midlands'),
    ('331', 'West Midlands'),
    ('332', 'West Midlands'),
    ('333', 'West Midlands'),
    ('334', 'West Midlands'),
    ('335', 'West Midlands'),
    ('336', 'West Midlands'),
    ('340', 'North West'),
    ('341', 'North West'),
    ('342', 'North West'),
    ('343', 'North West'),
    ('344', 'North West'),
    ('350', 'North West'),
    ('351', 'North West'),
    ('352', 'North West'),
    ('353', 'North West'),
    ('354', 'North West'),
    ('355', 'North West'),
    ('356', 'North West'),
    ('357', 'North West'),
    ('358', 'North West'),
    ('359', 'North West'),
    ('370', 'Yorkshire and The Humber'),
    ('371', 'Yorkshire and The Humber'),
    ('372', 'Yorkshire and The Humber'),
    ('373', 'Yorkshire and The Humber'),
    ('380', 'Yorkshire and The Humber'),
    ('381', 'Yorkshire and The Humber'),
    ('382', 'Yorkshire and The Humber'),
    ('383', 'Yorkshire and The Humber'),
    ('384', 'Yorkshire and The Humber'),
    ('390', 'North East'),
    ('391', 'North East'),
    ('392', 'North East'),
    ('393', 'North East'),
    ('394', 'North East'),
    ('420', 'South West'),
    ('800', 'South West'),
    ('801', 'South West'),
    ('802', 'South West'),
    ('803', 'South West'),
    ('805', 'North East'),
    ('806', 'North East'),
    ('807', 'North East'),
    ('808', 'North East'),
    ('810', 'Yorkshire and The Humber'),
    ('811', 'Yorkshire and The Humber'),
    ('812', 'Yorkshire and The Humber'),
    ('813', 'Yorkshire and The Humber'),
    ('815', 'Yorkshire and The Humber'),
    ('816', 'Yorkshire and The Humber'),
    ('820', 'East of England'),
    ('821', 'East of England'),
    ('822', 'East of England'),
    ('823', 'East of England'),
    ('825', 'South East'),
    ('826', 'South East'),
    ('830', 'East Midlands'),
    ('831', 'East Midlands'),
    ('835', 'South West'),
    ('836', 'South West'),
    ('837', 'South West'),
    ('838', 'South West'),
    ('839', 'South West'),
    ('840', 'North East'),
    ('841', 'North East'),
    ('845', 'South East'),
    ('846', 'South East'),
    ('850', 'South East'),
    ('851', 'South East'),
    ('852', 'South East'),
    ('855', 'East Midlands'),
    ('856', 'East Midlands'),
    ('857', 'East Midlands'),
    ('860', 'West Midlands'),
    ('861', 'West Midlands'),
    ('865', 'South West'),
    ('866', 'South West'),
    ('867', 'South East'),
    ('868', 'South East'),
    ('869', 'South East'),
    ('870', 'South East'),
    ('871', 'South East'),
    ('872', 'South East'),
    ('873', 'East of England'),
    ('874', 'East of England'),
    ('875', 'North West'),
    ('876', 'North West'),
    ('877', 'North West'),
    ('878', 'South West'),
    ('879', 'South West'),
    ('880', 'South West'),
    ('881', 'East of England'),
    ('882', 'East of England'),
    ('883', 'East of England'),
    ('884', 'West Midlands'),
    ('885', 'West Midlands'),
    ('886', 'South East'),
    ('887', 'South East'),
    ('888', 'North West'),
    ('889', 'North West'),
    ('890', 'North West'),
    ('891', 'East Midlands'),
    ('892', 'East Midlands'),
    ('893', 'West Midlands'),
    ('894', 'West Midlands'),
    ('895', 'North West'),
    ('896', 'North West'),
    ('908', 'South West'),
    ('909', 'North West'),
    ('916', 'South West'),
    ('919', 'East of England'),
    ('921', 'South East'),
    ('925', 'East Midlands'),
    ('926', 'East of England'),
    ('928', 'East Midlands'),
    ('929', 'North East'),
    ('931', 'South East'),
    ('933', 'South West'),
    ('935', 'East of England'),
    ('936', 'South East'),
    ('937', 'West Midlands'),
    ('938', 'South East'),
    ('940', 'East Midlands'),
    ('941', 'East Midlands'),
    ('942', 'North West'),
    ('943', 'North West')
) as v(dfe_code, region)
where t.dfe_code = v.dfe_code;

comment on column public.la_gss_crosswalk.region is
    'One of England''s 9 ONS regions (North East/North West/Yorkshire and The Humber/East Midlands/West Midlands/East of England/London/South East/South West). Null for the 22 Welsh (W06) rows -- Wales has no equivalent region tier in this taxonomy, not a gap to fill in later.';
